# Pipelines — Cross-Validation Mechanism (Phase 3 + Phase 5)

This notebook runs the project's four regression pipelines end to end and shows the full mechanism: k-Fold (k=5) cross-validation repeated over 5 seeds, scaling fitted only inside each training fold (no leakage), and the multi-criteria Top-3 model selection that bridges Pipeline 1 into Pipelines 3 and 4.

Pipelines:
1. **Pipeline 1** — Single-output, Original datasets, all 11 models
2. **Top-3 selection** — multi-criteria composite score (accuracy, generalization gap, fold stability, uncertainty, interpretability)
3. **Pipeline 2** — Multi-output, Original datasets, all 11 models
4. **Pipeline 3** — Single-output, Discrete-Input datasets, Top-3 models only
5. **Pipeline 4** — Multi-output, Discrete-Input datasets, Top-3 models only

All aggregated tables and raw per-fold tables are saved to `results/pipeline{1..4}/`, and the last cell shows the complete combined results.

Setup: make the repo root and `scripts/` importable, silence a harmless sklearn naming warning, and configure pandas to display full tables.

In [1]:
import sys
import warnings
from pathlib import Path

REPO_ROOT = Path.cwd().parent if (Path.cwd() / '..' / 'src').resolve().exists() else Path.cwd()
SCRIPTS_DIR = REPO_ROOT / 'scripts'
for p in (REPO_ROOT, SCRIPTS_DIR):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

warnings.filterwarnings('ignore', message='X does not have valid feature names.*')
warnings.filterwarnings('ignore', message='X has feature names, but.*')

import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 250)

from src.config import get_path
from _pipeline_common import run_pipeline, read_top3_models

print('Models registry check:')
from src.models.registry import available_models
print(available_models())

Models registry check:

['linear_regression', 'ridge', 'elasticnet', 'svr_rbf', 'gpr', 'random_forest', 'extra_trees', 'gradient_boosting', 'ann', 'xgboost', 'lightgbm']

## Pipeline 1 — Single-output, Original datasets, all models

For every dataset, every Level-A output target, every model and every seed, this runs 5-fold CV and aggregates mean/std of R2, RMSE, NRMSE, MAE plus the generalization gap and fold stability. Results are logged to MLflow and saved to `results/pipeline1/`.

In [2]:
agg1 = run_pipeline(mode='single', discrete=False, pipeline_id=1)
agg1.sort_values(['dataset', 'target', 'test_r2_mean'], ascending=[True, True, False])

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

[pipeline 1] results saved to C:\Users\mohammadhosein\Desktop\DeepLearning-miniProject\results\pipeline1

,dataset,mode,target,model,train_r2_mean,train_r2_std,train_rmse_mean,train_rmse_std,train_nrmse_mean,train_nrmse_std,train_mae_mean,train_mae_std,test_r2_mean,test_r2_std,test_rmse_mean,test_rmse_std,test_nrmse_mean,test_nrmse_std,test_mae_mean,test_mae_std,gap_r2,gap_rmse,stability_test_r2_std,stability_test_rmse_std
5,Dataset_0136,single_output,Elongation (%),lightgbm,0.960882,0.017741,0.523813,0.117612,0.048105,0.011329,0.369945,0.080881,0.755943,0.213604,1.119527,0.401198,0.149386,0.066139,0.846647,0.271502,0.204939,0.595714,0.213604,0.401198
10,Dataset_0136,single_output,Elongation (%),xgboost,0.954844,0.013501,0.576552,0.073590,0.052964,0.007967,0.459906,0.053263,0.642990,0.257581,1.408817,0.391650,0.187160,0.064389,1.126795,0.299539,0.311854,0.832265,0.257581,0.391650
3,Dataset_0136,single_output,Elongation (%),gpr,0.994785,0.014223,0.072521,0.180366,0.006853,0.017123,0.051817,0.129585,0.525892,0.208691,1.740030,0.622594,0.219837,0.055734,1.373682,0.514996,0.468893,1.667509,0.208691,0.622594
2,Dataset_0136,single_output,Elongation (%),extra_trees,0.879797,0.058299,0.929116,0.187140,0.085458,0.019408,0.692633,0.135063,0.493084,0.446675,1.728030,0.895053,0.218629,0.093130,1.354521,0.700489,0.386713,0.798914,0.446675,0.895053
7,Dataset_0136,single_output,Elongation (%),random_forest,0.784222,0.044020,1.270210,0.107989,0.116520,0.011760,0.892152,0.087986,0.365248,0.379903,1.983382,0.732653,0.251380,0.072291,1.519023,0.575792,0.418974,0.713172,0.379903,0.732653
4,Dataset_0136,single_output,Elongation (%),gradient_boosting,0.756827,0.191917,1.256765,0.570049,0.115254,0.051855,0.932487,0.435018,0.340285,0.495693,1.906810,0.667955,0.250669,0.087728,1.475976,0.470863,0.416542,0.650045,0.495693,0.667955
9,Dataset_0136,single_output,Elongation (%),svr_rbf,0.515936,0.049674,1.916508,0.148339,0.175415,0.011453,1.247647,0.116575,0.189060,0.309094,2.301843,0.776993,0.287991,0.055776,1.767154,0.597772,0.326876,0.385334,0.309094,0.776993
1,Dataset_0136,single_output,Elongation (%),elasticnet,0.243307,0.071797,2.396853,0.182446,0.219425,0.014750,1.851956,0.180962,-0.122252,0.471687,2.664968,0.776426,0.337558,0.065963,2.153175,0.584176,0.365559,0.268115,0.471687,0.776426
8,Dataset_0136,single_output,Elongation (%),ridge,0.245876,0.071986,2.392770,0.182871,0.219051,0.014797,1.826001,0.182784,-0.129702,0.507951,2.663187,0.787817,0.337495,0.070695,2.131934,0.583411,0.375578,0.270417,0.507951,0.787817
6,Dataset_0136,single_output,Elongation (%),linear_regression,0.246160,0.072058,2.392311,0.182941,0.219010,0.014807,1.812967,0.185283,-0.141316,0.528957,2.671702,0.796286,0.338675,0.073266,2.127950,0.586163,0.387477,0.279391,0.528957,0.796286
0,Dataset_0136,single_output,Elongation (%),ann,0.179706,0.365943,2.386783,0.636139,0.219471,0.060805,1.891556,0.577808,-0.560472,1.042542,3.036406,1.148131,0.390391,0.133715,2.508511,1.159825,0.740178,0.649623,1.042542,1.148131
16,Dataset_0136,single_output,Hardness (HV),lightgbm,0.993236,0.002266,0.444334,0.068402,0.021177,0.004051,0.345235,0.053135,0.945300,0.039858,1.047991,0.205022,0.072744,0.024194,0.864229,0.195432,0.047935,0.603658,0.039858,0.205022
21,Dataset_0136,single_output,Hardness (HV),xgboost,0.994058,0.001731,0.418787,0.053236,0.019913,0.003128,0.325753,0.044296,0.939942,0.059359,1.060734,0.282900,0.074109,0.031119,0.804763,0.244479,0.054116,0.641947,0.059359,0.282900
15,Dataset_0136,single_output,Hardness (HV),gradient_boosting,0.984684,0.008071,0.663181,0.150297,0.031575,0.008107,0.464555,0.086738,0.918096,0.064958,1.317755,0.387773,0.089664,0.032225,1.023023,0.313459,0.066588,0.654574,0.064958,0.387773
14,Dataset_0136,single_output,Hardness (HV),gpr,0.963041,0.009471,1.049163,0.101529,0.049954,0.007359,0.850328,0.087430,0.898811,0.079976,1.425535,0.310124,0.098679,0.034790,1.228239,0.333304,0.064229,0.376372,0.079976,0.310124
19,Dataset_0136,single_output,Hardness (HV),ridge,0.943111,0.008542,1.309828,0.073799,0.062228,0.006168,1.111687,0.075478,0.892572,0.080142,1.484197,0.341251,0.102489,0.035701,1.309863,0.338125,0.050538,0.174368,0.080142,0.341251
17,Dataset_0136,single_output,Hardness (HV),linear_regression,0.944199,0.008463,1.297185,0.074701,0.061627,0.006150,1.098334,0.076798,0.892273,0.080850,1.481720,0.331973,0.102367,0.035457,1.302544,0.328497,0.051926,0.184535,0.080850,0.331973
12,Dataset_0136,single_output,Hardness (HV),elasticnet,0.940412,0.008793,1.340604,0.072108,0.063692,0.006241,1.134469,0.077199,0.890525,0.079715,1.508191,0.354103,0.103926,0.035781,1.328791,0.346135,0.049887,0.167588,0.079715,0.354103
18,Dataset_0136,single_output,Hardness (HV),random_forest,0.927490,0.010189,1.478545,0.058814,0.070234,0.006318,1.222458,0.063553,0.739205,0.141143,2.458777,0.588997,0.163776,0.036732,2.119691,0.530366,0.188285,0.980232,0.141143,0.588997
13,Dataset_0136,single_output,Hardness (HV),extra_trees,0.940137,0.015785,1.333160,0.129752,0.063526,0.009704,1.102856,0.108092,0.668815,0.205739,2.707772,0.574509,0.183194,0.047156,2.290770,0.569709,0.271322,1.374612,0.205739,0.574509
20,Dataset_0136,single_output,Hardness (HV),svr_rbf,0.685587,0.030087,3.090402,0.193026,0.146177,0.005514,2.289094,0.120580,0.459151,0.200486,3.639871,0.943748,0.240331,0.044098,3.030140,0.786459,0.226437,0.549469,0.200486,0.943748
11,Dataset_0136,single_output,Hardness (HV),ann,-0.563806,0.807684,6.699300,1.679011,0.318000,0.084156,5.557448,1.404223,-3.236696,3.803060,8.983173,2.843968,0.621595,0.262643,7.706804,2.744281,2.672890,2.283873,3.803060,2.843968
32,Dataset_0136,single_output,Si Particle Size (um),xgboost,0.991477,0.003487,0.072915,0.012596,0.023981,0.006412,0.055169,0.009856,0.936503,0.051558,0.171167,0.096098,0.079904,0.033734,0.129268,0.068329,0.054974,0.098253,0.051558,0.096098
26,Dataset_0136,single_output,Si Particle Size (um),gradient_boosting,0.986089,0.008298,0.091193,0.025733,0.029890,0.009925,0.066003,0.017985,0.928459,0.046703,0.186374,0.078602,0.088440,0.028632,0.144951,0.058066,0.057630,0.095180,0.046703,0.078602
27,Dataset_0136,single_output,Si Particle Size (um),lightgbm,0.987374,0.002775,0.090769,0.010298,0.029391,0.003705,0.066498,0.005734,0.921288,0.055552,0.190657,0.104639,0.089510,0.034196,0.144237,0.070244,0.066086,0.099888,0.055552,0.104639
30,Dataset_0136,single_output,Si Particle Size (um),ridge,0.924369,0.008975,0.223490,0.017825,0.072297,0.006450,0.179001,0.013505,0.851308,0.085453,0.266148,0.081882,0.129720,0.036350,0.219032,0.065125,0.073061,0.042658,0.085453,0.081882
31,Dataset_0136,single_output,Si Particle Size (um),svr_rbf,0.967338,0.013437,0.145011,0.029748,0.046494,0.007304,0.105062,0.010495,0.850916,0.113764,0.281683,0.163251,0.127933,0.046077,0.211867,0.102953,0.116422,0.136672,0.113764,0.163251
28,Dataset_0136,single_output,Si Particle Size (um),linear_regression,0.925429,0.008951,0.221917,0.017883,0.071784,0.006410,0.178508,0.013915,0.846613,0.094190,0.267275,0.073316,0.131323,0.037810,0.219511,0.062696,0.078816,0.045358,0.094190,0.073316
25,Dataset_0136,single_output,Si Particle Size (um),gpr,0.971479,0.020652,0.120518,0.067794,0.038730,0.022611,0.095916,0.054840,0.845019,0.112616,0.265916,0.098920,0.129515,0.046093,0.212786,0.066841,0.126460,0.145398,0.112616,0.098920
23,Dataset_0136,single_output,Si Particle Size (um),elasticnet,0.904232,0.010259,0.251263,0.014925,0.081471,0.008168,0.193007,0.011235,0.841864,0.086768,0.284673,0.127060,0.134353,0.040091,0.229312,0.088068,0.062368,0.033410,0.086768,0.127060
29,Dataset_0136,single_output,Si Particle Size (um),random_forest,0.934393,0.009577,0.207734,0.015055,0.067239,0.006043,0.151802,0.008130,0.792126,0.150666,0.318236,0.155491,0.149167,0.052831,0.257202,0.115335,0.142267,0.110503,0.150666,0.155491
24,Dataset_0136,single_output,Si Particle Size (um),extra_trees,0.945116,0.009921,0.189554,0.015912,0.061490,0.007404,0.141530,0.011213,0.757563,0.117309,0.354843,0.145241,0.166958,0.043089,0.297038,0.113979,0.187553,0.165290,0.117309,0.145241
22,Dataset_0136,single_output,Si Particle Size (um),ann,0.888572,0.065278,0.259899,0.069749,0.084714,0.024296,0.206228,0.057950,0.698050,0.225597,0.358954,0.087056,0.179686,0.060140,0.296181,0.079664,0.190522,0.099056,0.225597,0.087056
36,Dataset_0136,single_output,Strain,gpr,0.999405,0.000206,0.613733,0.099648,0.006428,0.001140,0.486941,0.091892,0.995478,0.002644,1.470655,0.368590,0.022331,0.007028,1.195909,0.316250,0.003927,0.856922,0.002644,0.368590
43,Dataset_0136,single_output,Strain,xgboost,0.999116,0.000429,0.741377,0.148457,0.007762,0.001633,0.603808,0.111393,0.990390,0.007270,2.100767,0.734428,0.031570,0.011174,1.763716,0.599267,0.008726,1.359389,0.007270,0.734428
38,Dataset_0136,single_output,Strain,lightgbm,0.998554,0.000674,0.942708,0.190009,0.009879,0.002149,0.749185,0.153521,0.988552,0.008863,2.333258,0.993969,0.033998,0.011719,1.883566,0.823771,0.010002,1.390549,0.008863,0.993969
37,Dataset_0136,single_output,Strain,gradient_boosting,0.991043,0.011665,2.069313,1.243348,0.021615,0.013034,1.234973,0.563228,0.973110,0.020883,3.523175,1.484978,0.052080,0.020150,2.894388,1.256784,0.017933,1.453863,0.020883,1.484978
41,Dataset_0136,single_output,Strain,ridge,0.967533,0.003631,4.609672,0.275277,0.048141,0.002749,3.691366,0.267853,0.943682,0.032035,5.226845,1.052286,0.078881,0.021231,4.233666,0.909157,0.023851,0.617174,0.032035,1.052286
39,Dataset_0136,single_output,Strain,linear_regression,0.968645,0.003615,4.529865,0.282412,0.047306,0.002809,3.539461,0.284542,0.943533,0.036200,5.159327,1.177015,0.078208,0.024520,4.097365,0.895717,0.025112,0.629462,0.036200,1.177015
34,Dataset_0136,single_output,Strain,elasticnet,0.966126,0.003653,4.708710,0.265594,0.049178,0.002671,3.805081,0.254860,0.942628,0.031200,5.308556,1.064000,0.079883,0.020127,4.353587,0.945863,0.023497,0.599846,0.031200,1.064000
35,Dataset_0136,single_output,Strain,extra_trees,0.961398,0.007517,5.001823,0.333326,0.052314,0.004455,4.130131,0.253960,0.854595,0.107289,8.251102,2.405813,0.125026,0.045601,6.946541,2.037750,0.106804,3.249279,0.107289,2.405813
40,Dataset_0136,single_output,Strain,random_forest,0.946746,0.008858,5.881215,0.254587,0.061488,0.003844,4.649172,0.207076,0.828009,0.116366,9.018469,2.869850,0.135277,0.046330,7.553702,2.591810,0.118737,3.137254,0.116366,2.869850
33,Dataset_0136,single_output,Strain,ann,0.895533,0.034031,8.171977,1.372822,0.085511,0.015231,6.350698,1.213431,0.723835,0.216000,10.723108,3.823356,0.165557,0.070457,9.262674,3.183662,0.171698,2.551130,0.216000,3.823356
42,Dataset_0136,single_output,Strain,svr_rbf,0.179378,0.037081,23.228601,1.246443,0.242490,0.010165,19.147063,1.165151,-0.089569,0.476875,24.204368,6.182174,0.353336,0.058187,21.220542,5.466820,0.268947,0.975767,0.476875,6.182174
54,Dataset_0136,single_output,Temperature (°C),xgboost,0.999068,0.000319,0.904912,0.122478,0.007748,0.001217,0.726056,0.107212,0.991406,0.004269,2.520594,0.734421,0.030272,0.009012,2.156492,0.642343,0.007662,1.615682,0.004269,0.734421
47,Dataset_0136,single_output,Temperature (°C),gpr,0.998552,0.000589,1.121643,0.237432,0.009576,0.002075,0.845655,0.183845,0.991019,0.006602,2.433059,0.843652,0.029514,0.011382,1.919989,0.722392,0.007533,1.311416,0.006602,0.843652
49,Dataset_0136,single_output,Temperature (°C),lightgbm,0.998318,0.001258,1.154170,0.378056,0.009892,0.003341,0.913897,0.294058,0.988543,0.007627,2.877165,1.116503,0.034052,0.012495,2.476302,1.024329,0.009775,1.722995,0.007627,1.116503
48,Dataset_0136,single_output,Temperature (°C),gradient_boosting,0.993279,0.005614,2.251341,0.917738,0.019293,0.007949,1.481018,0.500767,0.980446,0.016392,3.698913,1.600970,0.043847,0.018047,3.114049,1.332297,0.012833,1.447572,0.016392,1.600970
52,Dataset_0136,single_output,Temperature (°C),ridge,0.947966,0.006808,6.864885,0.253221,0.058662,0.003360,6.243815,0.255349,0.914888,0.063494,7.589071,1.101534,0.093650,0.029785,7.002589,1.053518,0.033078,0.724185,0.063494,1.101534
50,Dataset_0136,single_output,Temperature (°C),linear_regression,0.949048,0.006751,6.792603,0.258764,0.058046,0.003386,6.251868,0.246953,0.914250,0.065390,7.547956,1.000852,0.093553,0.030408,7.034592,1.016041,0.034798,0.755353,0.065390,1.000852
45,Dataset_0136,single_output,Temperature (°C),elasticnet,0.946636,0.006892,6.952548,0.246699,0.059410,0.003328,6.245939,0.266833,0.914217,0.062713,7.658410,1.208200,0.094236,0.029636,6.993072,1.116744,0.032419,0.705862,0.062713,1.208200
46,Dataset_0136,single_output,Temperature (°C),extra_trees,0.958446,0.007553,6.125017,0.399508,0.052313,0.003823,5.174593,0.422795,0.844762,0.107098,10.136396,1.860385,0.126448,0.045581,8.741118,1.703079,0.113685,4.011379,0.107098,1.860385
51,Dataset_0136,single_output,Temperature (°C),random_forest,0.947030,0.007856,6.921078,0.217548,0.059148,0.003340,5.491589,0.216557,0.832476,0.109534,10.658400,2.692134,0.131167,0.046984,8.997308,2.627015,0.114553,3.737322,0.109534,2.692134
53,Dataset_0136,single_output,Temperature (°C),svr_rbf,0.113686,0.024547,28.469985,1.561507,0.242937,0.010742,22.164297,1.304581,-0.015908,0.249931,28.631454,6.928845,0.336700,0.056353,23.381512,5.679194,0.129594,0.161469,0.249931,6.928845
44,Dataset_0136,single_output,Temperature (°C),ann,-1.488719,0.842142,47.162171,7.903096,0.402623,0.068374,38.669624,7.231231,-4.039264,3.363449,56.796370,19.446974,0.699419,0.272186,48.498905,16.384346,2.550546,9.634199,3.363449,19.446974
65,Dataset_0136,single_output,Ultimate Compression Strength (MPa),xgboost,0.988521,0.003066,1.678926,0.204936,0.028063,0.003974,1.287597,0.152200,0.906388,0.104230,3.936300,1.163887,0.092117,0.044382,3.104711,0.756561,0.082133,2.257374,0.104230,1.163887
58,Dataset_0136,single_output,Ultimate Compression Strength (MPa),gpr,0.993525,0.005550,1.091239,0.664344,0.018184,0.011197,0.883568,0.550895,0.886909,0.115158,4.398085,1.064163,0.103128,0.045280,3.507762,0.903877,0.106616,3.306846,0.115158,1.064163
60,Dataset_0136,single_output,Ultimate Compression Strength (MPa),lightgbm,0.983182,0.006082,2.014149,0.370619,0.033658,0.006561,1.496083,0.233869,0.876345,0.164369,4.373000,1.504050,0.103339,0.057803,3.352230,1.074723,0.106837,2.358851,0.164369,1.504050
59,Dataset_0136,single_output,Ultimate Compression Strength (MPa),gradient_boosting,0.965346,0.017870,2.847338,0.729406,0.047747,0.013196,2.135921,0.606030,0.828760,0.169769,5.410014,1.756785,0.125484,0.057387,4.195883,1.014746,0.136586,2.562676,0.169769,1.756785
62,Dataset_0136,single_output,Ultimate Compression Strength (MPa),random_forest,0.906615,0.016220,4.814093,0.347512,0.080392,0.007089,3.840669,0.354728,0.685076,0.306677,7.388466,1.780025,0.172165,0.072617,6.249820,1.426978,0.221539,2.574372,0.306677,1.780025
57,Dataset_0136,single_output,Ultimate Compression Strength (MPa),extra_trees,0.917492,0.016542,4.519465,0.423357,0.075360,0.006830,3.634407,0.413035,0.649345,0.339286,7.862853,1.559462,0.183612,0.074203,6.715018,1.369747,0.268147,3.343388,0.339286,1.559462
56,Dataset_0136,single_output,Ultimate Compression Strength (MPa),elasticnet,0.741836,0.042689,8.006330,0.582011,0.133801,0.013089,6.483339,0.510829,0.525352,0.549004,8.902675,2.177621,0.210110,0.099604,7.202942,1.554057,0.216484,0.896345,0.549004,2.177621
63,Dataset_0136,single_output,Ultimate Compression Strength (MPa),ridge,0.743150,0.042654,7.985662,0.584267,0.133456,0.013106,6.444095,0.515305,0.522304,0.564035,8.887600,2.222026,0.210088,0.101507,7.172565,1.542271,0.220845,0.901939,0.564035,2.222026
61,Dataset_0136,single_output,Ultimate Compression Strength (MPa),linear_regression,0.744005,0.042642,7.972155,0.585820,0.133231,0.013119,6.379639,0.521322,0.513749,0.594171,8.892323,2.308415,0.210758,0.105110,7.124867,1.537833,0.230255,0.920168,0.594171,2.308415
64,Dataset_0136,single_output,Ultimate Compression Strength (MPa),svr_rbf,0.265014,0.021958,13.581846,0.533804,0.226567,0.010177,11.110227,0.528952,0.038435,0.241554,14.417621,2.787581,0.320635,0.043150,12.313619,2.618532,0.226579,0.835775,0.241554,2.787581
55,Dataset_0136,single_output,Ultimate Compression Strength (MPa),ann,-0.176950,0.371245,16.945005,2.357946,0.283007,0.041589,13.888849,1.782436,-1.480359,1.448516,21.885534,5.904206,0.499245,0.162197,19.025673,5.868077,1.303409,4.940530,1.448516,5.904206
76,Dataset_0136,single_output,wear rate,xgboost,0.991285,0.002849,0.088362,0.012391,0.022087,0.003644,0.071367,0.009929,0.945819,0.033836,0.189381,0.055450,0.073257,0.024391,0.150251,0.042413,0.045466,0.101019,0.033836,0.055450
71,Dataset_0136,single_output,wear rate,lightgbm,0.987034,0.004326,0.107736,0.019405,0.026880,0.005073,0.074199,0.011521,0.941968,0.034180,0.204053,0.084408,0.075453,0.025299,0.146957,0.057612,0.045066,0.096317,0.034180,0.084408
70,Dataset_0136,single_output,wear rate,gradient_boosting,0.974870,0.030157,0.140506,0.062947,0.035142,0.016071,0.093642,0.051616,0.915115,0.093602,0.235884,0.100644,0.088806,0.035169,0.180181,0.084237,0.059755,0.095378,0.093602,0.100644
69,Dataset_0136,single_output,wear rate,gpr,0.961536,0.013496,0.182924,0.041733,0.045648,0.010858,0.154203,0.037302,0.884360,0.060956,0.278948,0.049121,0.109652,0.029583,0.241307,0.050831,0.077176,0.096025,0.060956,0.049121
74,Dataset_0136,single_output,wear rate,ridge,0.925801,0.009868,0.261478,0.016107,0.065196,0.004784,0.207045,0.014683,0.874518,0.052906,0.299482,0.070992,0.114879,0.025031,0.246492,0.068855,0.051283,0.038004,0.052906,0.070992
72,Dataset_0136,single_output,wear rate,linear_regression,0.926866,0.009804,0.259589,0.016240,0.064725,0.004804,0.206090,0.014892,0.873363,0.057161,0.299956,0.065081,0.115429,0.025434,0.246554,0.066255,0.053503,0.040367,0.057161,0.065081
67,Dataset_0136,single_output,wear rate,elasticnet,0.909604,0.011731,0.288521,0.014093,0.071951,0.004773,0.218740,0.015033,0.860269,0.056406,0.319393,0.105036,0.120619,0.028550,0.255774,0.086374,0.049335,0.030872,0.056406,0.105036
75,Dataset_0136,single_output,wear rate,svr_rbf,0.967428,0.009449,0.171455,0.020680,0.042750,0.005415,0.127553,0.009203,0.851824,0.086596,0.332005,0.136630,0.123512,0.032384,0.258653,0.090571,0.115604,0.160549,0.086596,0.136630
73,Dataset_0136,single_output,wear rate,random_forest,0.925446,0.007647,0.262296,0.010650,0.065359,0.002957,0.195354,0.011473,0.780624,0.088880,0.405515,0.124746,0.151724,0.030113,0.326515,0.096416,0.144823,0.143218,0.088880,0.124746
68,Dataset_0136,single_output,wear rate,extra_trees,0.931556,0.013732,0.250421,0.023060,0.062445,0.006387,0.202042,0.016607,0.731647,0.127161,0.442105,0.121241,0.169052,0.044025,0.372384,0.109439,0.199909,0.191684,0.127161,0.121241
66,Dataset_0136,single_output,wear rate,ann,0.613400,0.389251,0.536543,0.282140,0.133971,0.070522,0.402586,0.239987,-0.540380,1.842550,0.861605,0.382859,0.359787,0.221793,0.724760,0.329489,1.153780,0.325062,1.842550,0.382859
82,Dataset_0172,single_output,Elongation (%),lightgbm,0.954454,0.009138,0.685765,0.076868,0.046914,0.004695,0.509155,0.061563,0.791419,0.100348,1.335207,0.366507,0.121497,0.036227,1.006260,0.274025,0.163035,0.649442,0.100348,0.366507
87,Dataset_0172,single_output,Elongation (%),xgboost,0.937451,0.010380,0.804070,0.063915,0.055064,0.004222,0.612583,0.054491,0.783658,0.101944,1.361788,0.319755,0.124617,0.035731,1.039659,0.257736,0.153793,0.557718,0.101944,0.319755
81,Dataset_0172,single_output,Elongation (%),gradient_boosting,0.861486,0.085916,1.153556,0.299844,0.079652,0.024592,0.874359,0.247027,0.650770,0.285295,1.661776,0.719025,0.151494,0.066168,1.274229,0.568441,0.210716,0.508221,0.285295,0.719025
84,Dataset_0172,single_output,Elongation (%),random_forest,0.855400,0.019864,1.223581,0.074476,0.083845,0.005754,0.898636,0.060159,0.628353,0.197564,1.818049,0.518023,0.162743,0.043906,1.413408,0.410077,0.227047,0.594468,0.197564,0.518023
79,Dataset_0172,single_output,Elongation (%),extra_trees,0.836441,0.046398,1.294763,0.186095,0.088641,0.012256,0.965483,0.145169,0.515785,0.398436,1.990255,0.609428,0.182823,0.069439,1.526131,0.452667,0.320656,0.695492,0.398436,0.609428

## Top-3 multi-criteria model selection (Phase 5)

Ranks models on a weighted composite of accuracy, generalization gap, fold stability, uncertainty and interpretability (weights from `configs/config.yaml`). Accuracy alone never decides the winners.

In [3]:
top3 = read_top3_models()
ranked = pd.read_csv(get_path('results_dir') / 'top3_models.csv')
print('Top-3 models selected for Pipelines 3 & 4:', top3)
ranked

Top-3 models selected for Pipelines 3 & 4: ['xgboost', 'gpr', 'lightgbm']

                model  test_r2_mean    gap_r2  stability_test_r2_std  composite_score  rank
0             xgboost      0.871311  0.108734               0.115522         0.875000     1
1                 gpr      0.810246  0.163230               0.133501         0.871881     2
2            lightgbm      0.864263  0.113688               0.130110         0.870147     3
3               ridge      0.658892  0.123215               0.209220         0.869257     4
4          elasticnet      0.644095  0.120036               0.202934         0.868510     5
5   linear_regression      0.654541  0.128270               0.220698         0.865336     6
6   gradient_boosting      0.816599  0.123288               0.154503         0.855406     7
7       random_forest      0.712026  0.196701               0.191210         0.811664     8
8         extra_trees      0.684289  0.237727               0.231631         0.789458     9
9             svr_rbf      0.442960  0.173536               0.185695         0.746706    10
10                ann     -0.844728  1.040735               1.388280         0.075000    11

## Pipeline 2 — Multi-output, Original datasets, all models

All Level-A outputs of a dataset are predicted jointly (models without native multi-output support are wrapped in `MultiOutputRegressor`). Results saved to `results/pipeline2/`.

In [4]:
agg2 = run_pipeline(mode='multi', discrete=False, pipeline_id=2)
agg2.sort_values(['dataset', 'test_r2_mean'], ascending=[True, False])

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(

[pipeline 2] results saved to C:\Users\mohammadhosein\Desktop\DeepLearning-miniProject\results\pipeline2

,dataset,mode,target,model,train_r2_mean,train_r2_std,train_rmse_mean,train_rmse_std,train_nrmse_mean,train_nrmse_std,train_mae_mean,train_mae_std,test_r2_mean,test_r2_std,test_rmse_mean,test_rmse_std,test_nrmse_mean,test_nrmse_std,test_mae_mean,test_mae_std,gap_r2,gap_rmse,stability_test_r2_std,stability_test_rmse_std
5,Dataset_0136,multi_output,ALL,lightgbm,0.986940,0.002575,0.999666,0.119463,0.002336,0.000279,0.573578,0.067925,0.916849,0.040665,2.332151,0.507603,0.005690,0.001186,1.387738,0.248628,0.070091,1.332485,0.040665,0.507603
10,Dataset_0136,multi_output,ALL,xgboost,0.988339,0.002089,0.824746,0.067778,0.001927,0.000158,0.504237,0.036046,0.907634,0.042894,2.098213,0.420922,0.005125,0.001035,1.319428,0.222191,0.080704,1.273467,0.042894,0.420922
3,Dataset_0136,multi_output,ALL,gpr,0.982631,0.011077,1.025418,0.319346,0.002395,0.000741,0.670978,0.211057,0.849696,0.045181,2.996164,0.767268,0.007307,0.001803,1.926026,0.456754,0.132935,1.970746,0.045181,0.767268
4,Dataset_0136,multi_output,ALL,gradient_boosting,0.950305,0.031441,1.736389,0.478930,0.004059,0.001128,0.915514,0.229864,0.840610,0.085026,3.037171,0.807665,0.007404,0.001901,1.861207,0.428873,0.109695,1.300782,0.085026,0.807665
8,Dataset_0136,multi_output,ALL,ridge,0.813972,0.014768,4.471607,0.188528,0.010448,0.000440,2.814716,0.119497,0.695653,0.118265,5.036838,0.717324,0.012308,0.001765,3.188020,0.352958,0.118319,0.565231,0.118265,0.717324
1,Dataset_0136,multi_output,ALL,elasticnet,0.807450,0.014462,4.512796,0.185448,0.010544,0.000433,2.847504,0.114391,0.693229,0.121044,5.073338,0.694770,0.012393,0.001677,3.216665,0.355897,0.114221,0.560542,0.121044,0.694770
6,Dataset_0136,multi_output,ALL,linear_regression,0.814908,0.014784,4.440092,0.190671,0.010374,0.000445,2.780981,0.127547,0.691781,0.123038,5.015872,0.788378,0.012264,0.001987,3.164769,0.366695,0.123127,0.575780,0.123038,0.788378
7,Dataset_0136,multi_output,ALL,random_forest,0.860288,0.009196,4.510286,0.137558,0.010539,0.000343,2.802921,0.072051,0.651238,0.120753,6.797635,1.182677,0.016609,0.002882,4.287780,0.714491,0.209050,2.287349,0.120753,1.182677
2,Dataset_0136,multi_output,ALL,extra_trees,0.890586,0.010803,3.999818,0.177822,0.009346,0.000425,2.587063,0.100988,0.650090,0.119003,6.387095,1.267096,0.015622,0.003177,4.155883,0.812164,0.240496,2.387278,0.119003,1.267096
9,Dataset_0136,multi_output,ALL,svr_rbf,0.527767,0.012060,14.874058,0.705973,0.034748,0.001536,8.027278,0.365490,0.326273,0.140661,15.355437,3.305093,0.037318,0.007037,8.883355,1.747155,0.201494,0.481379,0.140661,3.305093
0,Dataset_0136,multi_output,ALL,ann,-0.208461,0.221911,18.415544,1.612690,0.043028,0.003767,9.941984,0.839881,-1.745871,1.415587,23.446381,5.550949,0.057389,0.013962,13.218710,3.257763,1.537410,5.030837,1.415587,5.550949
21,Dataset_0172,multi_output,ALL,xgboost,0.977683,0.003122,1.454139,0.160005,0.007980,0.000911,0.677201,0.054673,0.918830,0.024416,2.648487,0.647393,0.015247,0.003563,1.231394,0.215759,0.058853,1.194348,0.024416,0.647393
16,Dataset_0172,multi_output,ALL,lightgbm,0.984865,0.002210,1.023234,0.143667,0.005612,0.000791,0.520181,0.053485,0.916135,0.026448,2.631003,0.622997,0.015161,0.003451,1.277764,0.250446,0.068730,1.607769,0.026448,0.622997
15,Dataset_0172,multi_output,ALL,gradient_boosting,0.954635,0.018727,1.983874,0.469143,0.010877,0.002531,0.945804,0.197627,0.877781,0.060708,3.089550,0.727688,0.017793,0.003973,1.518185,0.314433,0.076855,1.105676,0.060708,0.727688
14,Dataset_0172,multi_output,ALL,gpr,0.971315,0.007773,1.315679,0.202893,0.007220,0.001131,0.714219,0.106524,0.854201,0.043244,2.959497,0.474882,0.017103,0.002802,1.567814,0.193736,0.117115,1.643818,0.043244,0.474882
19,Dataset_0172,multi_output,ALL,ridge,0.779450,0.014015,4.072879,0.168293,0.022347,0.001041,2.119895,0.086269,0.704414,0.068260,4.374238,0.658353,0.025252,0.003884,2.284560,0.281150,0.075036,0.301359,0.068260,0.658353
17,Dataset_0172,multi_output,ALL,linear_regression,0.779682,0.014023,4.070473,0.168401,0.022333,0.001041,2.114222,0.086572,0.702948,0.070450,4.375206,0.674622,0.025259,0.003991,2.280261,0.280647,0.076734,0.304733,0.070450,0.674622
12,Dataset_0172,multi_output,ALL,elasticnet,0.771283,0.013754,4.096107,0.167167,0.022474,0.001036,2.149641,0.085475,0.700754,0.061966,4.392667,0.628134,0.025356,0.003677,2.312321,0.283420,0.070529,0.296560,0.061966,0.628134
18,Dataset_0172,multi_output,ALL,random_forest,0.832776,0.013205,2.972084,0.154995,0.016305,0.000875,1.715071,0.086176,0.665628,0.077900,4.432674,0.687971,0.025619,0.004139,2.532184,0.352822,0.167148,1.460590,0.077900,0.687971
20,Dataset_0172,multi_output,ALL,svr_rbf,0.721582,0.010722,7.182102,0.203992,0.039393,0.000939,3.232445,0.090913,0.606057,0.061414,7.552483,1.204148,0.043538,0.006552,3.679238,0.501615,0.115525,0.370381,0.061414,1.204148
13,Dataset_0172,multi_output,ALL,extra_trees,0.817314,0.018897,3.102364,0.160033,0.017017,0.000863,1.842550,0.120262,0.601538,0.087887,4.773931,0.561014,0.027607,0.003578,2.823757,0.334759,0.215776,1.671567,0.087887,0.561014
11,Dataset_0172,multi_output,ALL,ann,0.500547,0.057914,7.240404,0.406712,0.039735,0.002551,3.845207,0.232540,0.019625,0.297831,9.138487,1.423516,0.052800,0.008497,5.054076,0.773929,0.480923,1.898083,0.297831,1.423516
32,Dataset_3772,multi_output,ALL,xgboost,0.970795,0.004768,1.427529,0.232943,0.007841,0.001344,0.701445,0.074792,0.772938,0.155423,3.464469,1.017304,0.020036,0.006268,1.689501,0.394142,0.197856,2.036940,0.155423,1.017304
27,Dataset_3772,multi_output,ALL,lightgbm,0.958450,0.008175,1.787715,0.363230,0.009819,0.002057,0.810085,0.086508,0.738770,0.194615,3.661759,1.295298,0.021177,0.007899,1.748661,0.431267,0.219680,1.874045,0.194615,1.295298
25,Dataset_3772,multi_output,ALL,gpr,0.958590,0.016143,1.492653,0.363942,0.008202,0.002059,0.792209,0.186742,0.729610,0.119628,3.602656,0.890361,0.020814,0.005550,1.872362,0.375317,0.228981,2.110003,0.119628,0.890361
26,Dataset_3772,multi_output,ALL,gradient_boosting,0.910555,0.029210,2.243267,0.392117,0.012323,0.002260,1.129948,0.181404,0.721802,0.158628,3.816380,1.059064,0.021984,0.006209,1.990631,0.467183,0.188753,1.573113,0.158628,1.059064
30,Dataset_3772,multi_output,ALL,ridge,0.740153,0.020946,4.276118,0.286344,0.023463,0.001670,2.210152,0.118443,0.561907,0.172356,4.764047,1.193664,0.027477,0.007185,2.476528,0.508863,0.178246,0.487928,0.172356,1.193664
28,Dataset_3772,multi_output,ALL,linear_regression,0.741006,0.020954,4.269684,0.286951,0.023427,0.001674,2.200304,0.119740,0.553998,0.183780,4.780018,1.211853,0.027581,0.007340,2.480347,0.499900,0.187007,0.510334,0.183780,1.211853
23,Dataset_3772,multi_output,ALL,elasticnet,0.696332,0.020921,4.287379,0.285300,0.023524,0.001665,2.235519,0.117976,0.518648,0.176942,4.764953,1.186624,0.027475,0.007115,2.498162,0.516712,0.177684,0.477575,0.176942,1.186624
29,Dataset_3772,multi_output,ALL,random_forest,0.809908,0.015100,2.967794,0.152518,0.016284,0.000930,1.679826,0.069248,0.517527,0.188431,4.803601,1.006338,0.027678,0.006159,2.722470,0.511070,0.292381,1.835807,0.188431,1.006338
31,Dataset_3772,multi_output,ALL,svr_rbf,0.635631,0.013407,6.930109,0.310366,0.038003,0.001451,3.241572,0.169477,0.443225,0.093442,7.331517,1.599469,0.041988,0.008594,3.781383,0.764431,0.192406,0.401409,0.093442,1.599469
24,Dataset_3772,multi_output,ALL,extra_trees,0.821462,0.035016,2.754243,0.184381,0.015108,0.001012,1.594141,0.112142,0.407054,0.211249,4.982067,1.045612,0.028719,0.006446,2.914263,0.548429,0.414408,2.227824,0.211249,1.045612
22,Dataset_3772,multi_output,ALL,ann,0.024377,0.369785,9.260100,1.620947,0.050859,0.009307,4.949634,0.919412,-1.237891,1.204500,11.161792,2.952913,0.064431,0.017937,6.230338,1.520102,1.262269,1.901692,1.204500,2.952913

## Pipeline 3 — Single-output, Discrete-Input datasets, Top-3 models only

Repeats the single-output protocol on the discretized inputs, restricted to the Top-3 models to keep runtime reasonable, as required by the assignment. Results saved to `results/pipeline3/`.

In [5]:
agg3 = run_pipeline(mode='single', discrete=True, pipeline_id=3, models=top3)
agg3.sort_values(['dataset', 'target', 'test_r2_mean'], ascending=[True, True, False])

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(
C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

C:\Users\mohammadhosein\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py:440: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-06. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

[pipeline 3] results saved to C:\Users\mohammadhosein\Desktop\DeepLearning-miniProject\results\pipeline3

,dataset,mode,target,model,train_r2_mean,train_r2_std,train_rmse_mean,train_rmse_std,train_nrmse_mean,train_nrmse_std,train_mae_mean,train_mae_std,test_r2_mean,test_r2_std,test_rmse_mean,test_rmse_std,test_nrmse_mean,test_nrmse_std,test_mae_mean,test_mae_std,gap_r2,gap_rmse,stability_test_r2_std,stability_test_rmse_std
1,Dataset_0136,single_output,Elongation (%),lightgbm,0.960882,0.017741,0.523813,0.117612,0.048105,0.011329,0.369945,0.080881,0.755943,0.213604,1.119527,0.401198,0.149386,0.066139,0.846647,0.271502,0.204939,0.595714,0.213604,0.401198
2,Dataset_0136,single_output,Elongation (%),xgboost,0.954844,0.013501,0.576552,0.073590,0.052964,0.007967,0.459906,0.053263,0.642990,0.257581,1.408817,0.391650,0.187160,0.064389,1.126795,0.299539,0.311854,0.832265,0.257581,0.391650
0,Dataset_0136,single_output,Elongation (%),gpr,0.970526,0.049952,0.269014,0.369541,0.025144,0.034427,0.185518,0.255015,0.447776,0.237686,1.898647,0.726595,0.236899,0.062108,1.442791,0.585615,0.522750,1.629633,0.237686,0.726595
4,Dataset_0136,single_output,Hardness (HV),lightgbm,0.993236,0.002266,0.444334,0.068402,0.021177,0.004051,0.345235,0.053135,0.945300,0.039858,1.047991,0.205022,0.072744,0.024194,0.864229,0.195432,0.047935,0.603658,0.039858,0.205022
5,Dataset_0136,single_output,Hardness (HV),xgboost,0.994058,0.001731,0.418787,0.053236,0.019913,0.003128,0.325753,0.044296,0.939942,0.059359,1.060734,0.282900,0.074109,0.031119,0.804763,0.244479,0.054116,0.641947,0.059359,0.282900
3,Dataset_0136,single_output,Hardness (HV),gpr,0.976475,0.006927,0.834946,0.092597,0.039791,0.006572,0.666932,0.074890,0.927821,0.054947,1.216244,0.255219,0.083863,0.028108,1.028893,0.261965,0.048654,0.381297,0.054947,0.255219
8,Dataset_0136,single_output,Si Particle Size (um),xgboost,0.991477,0.003487,0.072915,0.012596,0.023981,0.006412,0.055169,0.009856,0.936503,0.051558,0.171167,0.096098,0.079904,0.033734,0.129268,0.068329,0.054974,0.098253,0.051558,0.096098
7,Dataset_0136,single_output,Si Particle Size (um),lightgbm,0.987374,0.002775,0.090769,0.010298,0.029391,0.003705,0.066498,0.005734,0.921288,0.055552,0.190657,0.104639,0.089510,0.034196,0.144237,0.070244,0.066086,0.099888,0.055552,0.104639
6,Dataset_0136,single_output,Si Particle Size (um),gpr,0.980915,0.012635,0.103763,0.045301,0.033454,0.015226,0.079450,0.034616,0.887336,0.089865,0.225994,0.097740,0.108882,0.042424,0.174669,0.065889,0.093578,0.122230,0.089865,0.097740
11,Dataset_0136,single_output,Strain,xgboost,0.999116,0.000429,0.741377,0.148457,0.007762,0.001633,0.603808,0.111393,0.990390,0.007270,2.100767,0.734428,0.031570,0.011174,1.763716,0.599267,0.008726,1.359389,0.007270,0.734428
10,Dataset_0136,single_output,Strain,lightgbm,0.998554,0.000674,0.942708,0.190009,0.009879,0.002149,0.749185,0.153521,0.988552,0.008863,2.333258,0.993969,0.033998,0.011719,1.883566,0.823771,0.010002,1.390549,0.008863,0.993969
9,Dataset_0136,single_output,Strain,gpr,0.997824,0.000753,1.174416,0.228336,0.012262,0.002332,0.911356,0.174537,0.988254,0.006762,2.319261,0.468817,0.035800,0.011439,1.794049,0.425380,0.009570,1.144845,0.006762,0.468817
14,Dataset_0136,single_output,Temperature (°C),xgboost,0.999068,0.000319,0.904912,0.122478,0.007748,0.001217,0.726056,0.107212,0.991406,0.004269,2.520594,0.734421,0.030272,0.009012,2.156492,0.642343,0.007662,1.615682,0.004269,0.734421
13,Dataset_0136,single_output,Temperature (°C),lightgbm,0.998318,0.001258,1.154170,0.378056,0.009892,0.003341,0.913897,0.294058,0.988543,0.007627,2.877165,1.116503,0.034052,0.012495,2.476302,1.024329,0.009775,1.722995,0.007627,1.116503
12,Dataset_0136,single_output,Temperature (°C),gpr,0.996018,0.000701,1.896585,0.135044,0.016195,0.001207,1.637683,0.154103,0.985878,0.007818,3.129273,0.552291,0.038417,0.011302,2.722468,0.493053,0.010140,1.232689,0.007818,0.552291
17,Dataset_0136,single_output,Ultimate Compression Strength (MPa),xgboost,0.988521,0.003066,1.678926,0.204936,0.028063,0.003974,1.287597,0.152200,0.906388,0.104230,3.936300,1.163887,0.092117,0.044382,3.104711,0.756561,0.082133,2.257374,0.104230,1.163887
15,Dataset_0136,single_output,Ultimate Compression Strength (MPa),gpr,0.994540,0.004778,0.992919,0.638025,0.016607,0.010831,0.806596,0.529056,0.890688,0.118536,4.280934,1.120566,0.100663,0.046642,3.384052,0.908944,0.103852,3.288014,0.118536,1.120566
16,Dataset_0136,single_output,Ultimate Compression Strength (MPa),lightgbm,0.983182,0.006082,2.014149,0.370619,0.033658,0.006561,1.496083,0.233869,0.876345,0.164369,4.373000,1.504050,0.103339,0.057803,3.352230,1.074723,0.106837,2.358851,0.164369,1.504050
20,Dataset_0136,single_output,wear rate,xgboost,0.991285,0.002849,0.088362,0.012391,0.022087,0.003644,0.071367,0.009929,0.945819,0.033836,0.189381,0.055450,0.073257,0.024391,0.150251,0.042413,0.045466,0.101019,0.033836,0.055450
19,Dataset_0136,single_output,wear rate,lightgbm,0.987034,0.004326,0.107736,0.019405,0.026880,0.005073,0.074199,0.011521,0.941968,0.034180,0.204053,0.084408,0.075453,0.025299,0.146957,0.057612,0.045066,0.096317,0.034180,0.084408
18,Dataset_0136,single_output,wear rate,gpr,0.979842,0.011404,0.127370,0.046184,0.031865,0.011928,0.105613,0.039256,0.916201,0.036616,0.241431,0.045894,0.094059,0.021920,0.203203,0.043733,0.063641,0.114061,0.036616,0.045894
22,Dataset_0172,single_output,Elongation (%),lightgbm,0.954454,0.009138,0.685765,0.076868,0.046914,0.004695,0.509155,0.061563,0.791419,0.100348,1.335207,0.366507,0.121497,0.036227,1.006260,0.274025,0.163035,0.649442,0.100348,0.366507
23,Dataset_0172,single_output,Elongation (%),xgboost,0.937451,0.010380,0.804070,0.063915,0.055064,0.004222,0.612583,0.054491,0.783658,0.101944,1.361788,0.319755,0.124617,0.035731,1.039659,0.257736,0.153793,0.557718,0.101944,0.319755
21,Dataset_0172,single_output,Elongation (%),gpr,0.924686,0.041568,0.822416,0.322508,0.056562,0.022519,0.598645,0.233984,0.459761,0.222904,2.176189,0.464766,0.197559,0.047730,1.669340,0.352533,0.464924,1.353773,0.222904,0.464766
26,Dataset_0172,single_output,Hardness (HV),xgboost,0.988171,0.003221,0.658746,0.098058,0.025275,0.004243,0.496996,0.068456,0.949639,0.029015,1.266839,0.328805,0.063363,0.020284,0.943387,0.244167,0.038532,0.608093,0.029015,0.328805
25,Dataset_0172,single_output,Hardness (HV),lightgbm,0.990528,0.002742,0.588705,0.099201,0.022569,0.004066,0.436004,0.061639,0.941274,0.032807,1.373056,0.360676,0.068608,0.022125,1.059693,0.269140,0.049253,0.784351,0.032807,0.360676
24,Dataset_0172,single_output,Hardness (HV),gpr,0.977805,0.006173,0.902247,0.144059,0.034542,0.005596,0.699403,0.103768,0.926330,0.058518,1.493015,0.441916,0.075285,0.030039,1.166800,0.283539,0.051474,0.590768,0.058518,0.441916
29,Dataset_0172,single_output,Si Particle Size (um),xgboost,0.993262,0.001149,0.076228,0.007225,0.020373,0.001586,0.054159,0.004470,0.978621,0.008628,0.130322,0.039556,0.043899,0.008366,0.093640,0.019376,0.014642,0.054094,0.008628,0.039556
27,Dataset_0172,single_output,Si Particle Size (um),gpr,0.991059,0.004628,0.082438,0.031652,0.022247,0.008742,0.057903,0.021629,0.971468,0.013028,0.146321,0.039052,0.050353,0.013079,0.103739,0.021274,0.019590,0.063884,0.013028,0.039052
28,Dataset_0172,single_output,Si Particle Size (um),lightgbm,0.994917,0.001466,0.065601,0.009472,0.017675,0.003323,0.045955,0.006747,0.971442,0.018058,0.146138,0.053247,0.049031,0.012263,0.101446,0.026127,0.023475,0.080537,0.018058,0.053247
31,Dataset_0172,single_output,Ultimate Compression Strength (MPa),lightgbm,0.987612,0.003665,2.090869,0.352704,0.024952,0.004371,1.547911,0.237583,0.894812,0.059171,5.520350,1.449289,0.085178,0.025230,4.082725,1.143946,0.092799,3.429481,0.059171,1.449289
32,Dataset_0172,single_output,Ultimate Compression Strength (MPa),xgboost,0.973378,0.006765,3.075045,0.370948,0.036726,0.004936,2.155261,0.218058,0.893813,0.057481,5.588709,1.495664,0.085749,0.023745,3.970063,0.958155,0.079565,2.513664,0.057481,1.495664
30,Dataset_0172,single_output,Ultimate Compression Strength (MPa),gpr,0.984299,0.005523,2.343451,0.410597,0.027958,0.005023,1.768210,0.290428,0.880452,0.064927,5.854225,1.249453,0.091379,0.027225,4.377985,0.788412,0.103848,3.510774,0.064927,1.249453
35,Dataset_0172,single_output,wear rate,xgboost,0.996152,0.000442,0.089248,0.005942,0.015201,0.001120,0.067008,0.005464,0.988418,0.005073,0.146739,0.041609,0.030715,0.006172,0.110221,0.024934,0.007733,0.057492,0.005073,0.041609
34,Dataset_0172,single_output,wear rate,lightgbm,0.996815,0.000597,0.080895,0.007554,0.013785,0.001413,0.061882,0.005529,0.981729,0.009290,0.183951,0.059420,0.038465,0.009266,0.138693,0.036724,0.015086,0.103056,0.009290,0.059420
33,Dataset_0172,single_output,wear rate,gpr,0.989458,0.001100,0.147650,0.006987,0.025143,0.001341,0.118627,0.006845,0.979592,0.006143,0.194588,0.026411,0.041389,0.005582,0.160831,0.028306,0.009866,0.046939,0.006143,0.026411
38,Dataset_3772,single_output,Elongation (%),xgboost,0.932288,0.018992,0.835780,0.113182,0.061743,0.009101,0.678353,0.087323,0.527524,0.291668,1.906369,0.507596,0.211289,0.066529,1.515894,0.382573,0.404763,1.070589,0.291668,0.507596
37,Dataset_3772,single_output,Elongation (%),lightgbm,0.912433,0.032959,0.939375,0.142131,0.069425,0.011354,0.672326,0.115874,0.488935,0.384694,1.884728,0.465330,0.214141,0.078989,1.397947,0.385752,0.423497,0.945353,0.384694,0.465330
36,Dataset_3772,single_output,Elongation (%),gpr,0.918940,0.055961,0.833287,0.405451,0.061220,0.028937,0.627327,0.300459,0.358922,0.238438,2.379263,0.744218,0.254970,0.051373,1.885284,0.647649,0.560018,1.545976,0.238438,0.744218
41,Dataset_3772,single_output,Hardness (HV),xgboost,0.985325,0.005397,0.660798,0.141979,0.032599,0.007120,0.511500,0.101418,0.854979,0.201732,1.655039,0.606722,0.118375,0.066249,1.277840,0.420739,0.130346,0.994241,0.201732,0.606722
40,Dataset_3772,single_output,Hardness (HV),lightgbm,0.972321,0.011144,0.897710,0.215836,0.044394,0.011354,0.647452,0.139220,0.820682,0.241897,1.828338,0.645435,0.132018,0.072469,1.423277,0.478333,0.151640,0.930628,0.241897,0.645435
39,Dataset_3772,single_output,Hardness (HV),gpr,0.975683,0.014671,0.809447,0.317742,0.039822,0.015660,0.606547,0.239595,0.812742,0.260549,1.824911,0.748298,0.132416,0.079813,1.394578,0.502554,0.162941,1.015463,0.260549,0.748298
44,Dataset_3772,single_output,Si Particle Size (um),xgboost,0.983774,0.004513,0.026183,0.003097,0.034563,0.005963,0.019312,0.002621,0.925959,0.050311,0.050198,0.025224,0.090063,0.032863,0.039668,0.018491,0.057816,0.024015,0.050311,0.025224
42,Dataset_3772,single_output,Si Particle Size (um),gpr,0.975663,0.015021,0.029481,0.014892,0.038047,0.019443,0.020829,0.010166,0.920025,0.058747,0.050330,0.025200,0.092114,0.037713,0.039222,0.015576,0.055637,0.020849,0.058747,0.025200
43,Dataset_3772,single_output,Si Particle Size (um),lightgbm,0.979989,0.006943,0.028881,0.003464,0.038305,0.007823,0.022418,0.003202,0.905708,0.048266,0.056510,0.022288,0.102645,0.027825,0.046107,0.016460,0.074281,0.027630,0.048266,0.022288
45,Dataset_3772,single_output,Ultimate Compression Strength (MPa),gpr,0.981289,0.015828,2.004501,1.132377,0.029195,0.016912,1.531708,0.878895,0.665077,0.437074,7.448087,2.056809,0.166127,0.086834,5.800849,1.626198,0.316212,5.443587,0.437074,2.056809
47,Dataset_3772,single_output,Ultimate Compression Strength (MPa),xgboost,0.967130,0.012864,2.996212,0.557381,0.043968,0.009133,2.233381,0.364188,0.636589,0.610912,7.231387,2.433512,0.164780,0.104221,5.492317,1.750188,0.330541,4.235175,0.610912,2.433512
46,Dataset_3772,single_output,Ultimate Compression Strength (MPa),lightgbm,0.947432,0.023743,3.759862,0.862396,0.055125,0.013378,2.638569,0.417217,0.568531,0.736341,7.623921,3.134473,0.174756,0.122993,5.750090,2.166697,0.378901,3.864060,0.736341,3.134473
50,Dataset_3772,single_output,wear rate,xgboost,0.985457,0.004159,0.080849,0.008171,0.028894,0.004050,0.064676,0.007330,0.919641,0.089009,0.152914,0.040710,0.087131,0.040547,0.121785,0.035655,0.065816,0.072066,0.089009,0.040710
48,Dataset_3772,single_output,wear rate,gpr,0.969624,0.007299,0.117167,0.009565,0.041835,0.004909,0.094424,0.008301,0.917498,0.049297,0.163253,0.030868,0.092527,0.029418,0.135384,0.033464,0.052126,0.046086,0.049297,0.030868
49,Dataset_3772,single_output,wear rate,lightgbm,0.980074,0.004878,0.095002,0.008949,0.033889,0.004015,0.069659,0.006492,0.909991,0.056940,0.174906,0.052621,0.095934,0.031208,0.125883,0.046300,0.070083,0.079904,0.056940,0.052621

## Pipeline 4 — Multi-output, Discrete-Input datasets, Top-3 models only

Multi-output protocol on discretized inputs, Top-3 models only. Results saved to `results/pipeline4/`.

In [6]:
agg4 = run_pipeline(mode='multi', discrete=True, pipeline_id=4, models=top3)
agg4.sort_values(['dataset', 'test_r2_mean'], ascending=[True, False])

[pipeline 4] results saved to C:\Users\mohammadhosein\Desktop\DeepLearning-miniProject\results\pipeline4

,dataset,mode,target,model,train_r2_mean,train_r2_std,train_rmse_mean,train_rmse_std,train_nrmse_mean,train_nrmse_std,train_mae_mean,train_mae_std,test_r2_mean,test_r2_std,test_rmse_mean,test_rmse_std,test_nrmse_mean,test_nrmse_std,test_mae_mean,test_mae_std,gap_r2,gap_rmse,stability_test_r2_std,stability_test_rmse_std
1,Dataset_0136,multi_output,ALL,lightgbm,0.986940,0.002575,0.999666,0.119463,0.002336,0.000279,0.573578,0.067925,0.916849,0.040665,2.332151,0.507603,0.005690,0.001186,1.387738,0.248628,0.070091,1.332485,0.040665,0.507603
2,Dataset_0136,multi_output,ALL,xgboost,0.988339,0.002089,0.824746,0.067778,0.001927,0.000158,0.504237,0.036046,0.907634,0.042894,2.098213,0.420922,0.005125,0.001035,1.319428,0.222191,0.080704,1.273467,0.042894,0.420922
0,Dataset_0136,multi_output,ALL,gpr,0.968314,0.012855,1.545385,0.332392,0.003610,0.000772,0.996167,0.213521,0.845683,0.050161,3.322324,0.678225,0.008107,0.001581,2.157118,0.384885,0.122631,1.776938,0.050161,0.678225
5,Dataset_0172,multi_output,ALL,xgboost,0.977683,0.003122,1.454139,0.160005,0.007980,0.000911,0.677201,0.054673,0.918830,0.024416,2.648487,0.647393,0.015247,0.003563,1.231394,0.215759,0.058853,1.194348,0.024416,0.647393
4,Dataset_0172,multi_output,ALL,lightgbm,0.984865,0.002210,1.023234,0.143667,0.005612,0.000791,0.520181,0.053485,0.916135,0.026448,2.631003,0.622997,0.015161,0.003451,1.277764,0.250446,0.068730,1.607769,0.026448,0.622997
3,Dataset_0172,multi_output,ALL,gpr,0.969027,0.006423,1.337294,0.170365,0.007339,0.000963,0.704073,0.081697,0.855493,0.044612,2.888986,0.545157,0.016686,0.003146,1.490980,0.208056,0.113534,1.551692,0.044612,0.545157
8,Dataset_3772,multi_output,ALL,xgboost,0.970795,0.004768,1.427529,0.232943,0.007841,0.001344,0.701445,0.074792,0.772938,0.155423,3.464469,1.017304,0.020036,0.006268,1.689501,0.394142,0.197856,2.036940,0.155423,1.017304
6,Dataset_3772,multi_output,ALL,gpr,0.958615,0.013352,1.505226,0.302534,0.008270,0.001733,0.777055,0.148067,0.748887,0.107826,3.494039,0.910243,0.020188,0.005645,1.772996,0.381751,0.209728,1.988814,0.107826,0.910243
7,Dataset_3772,multi_output,ALL,lightgbm,0.958450,0.008175,1.787715,0.363230,0.009819,0.002057,0.810085,0.086508,0.738770,0.194615,3.661759,1.295298,0.021177,0.007899,1.748661,0.431267,0.219680,1.874045,0.194615,1.295298

## Final Summary — Complete Cross-Validation Results (All 4 Pipelines)

All four aggregated tables combined, displayed in full, and saved as one `pipelines_summary.csv` under `results/`.

In [7]:
agg1_tagged = agg1.copy(); agg1_tagged.insert(0, 'pipeline', 'pipeline1_single_original')
agg2_tagged = agg2.copy(); agg2_tagged.insert(0, 'pipeline', 'pipeline2_multi_original')
agg3_tagged = agg3.copy(); agg3_tagged.insert(0, 'pipeline', 'pipeline3_single_discrete')
agg4_tagged = agg4.copy(); agg4_tagged.insert(0, 'pipeline', 'pipeline4_multi_discrete')

summary = pd.concat([agg1_tagged, agg2_tagged, agg3_tagged, agg4_tagged], ignore_index=True)
summary_path = get_path('results_dir') / 'pipelines_summary.csv'
summary.to_csv(summary_path, index=False)

print('=' * 90)
print('COMBINED AGGREGATED RESULTS — Pipelines 1-4')
print('=' * 90)
display(summary)

print()
print('=' * 90)
print('TOP-3 MODELS (selected from Pipeline 1, used in Pipelines 3 & 4):', top3)
print('=' * 90)

print()
print('All pipeline results (fold-level + aggregated CSVs) saved to:', get_path('results_dir').resolve())
print('Combined summary saved to:', summary_path.resolve())

==========================================================================================
COMBINED AGGREGATED RESULTS — Pipelines 1-4
==========================================================================================

,pipeline,dataset,mode,target,model,train_r2_mean,train_r2_std,train_rmse_mean,train_rmse_std,train_nrmse_mean,train_nrmse_std,train_mae_mean,train_mae_std,test_r2_mean,test_r2_std,test_rmse_mean,test_rmse_std,test_nrmse_mean,test_nrmse_std,test_mae_mean,test_mae_std,gap_r2,gap_rmse,stability_test_r2_std,stability_test_rmse_std
0,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),ann,0.179706,0.365943,2.386783,0.636139,0.219471,0.060805,1.891556,0.577808,-0.560472,1.042542,3.036406,1.148131,0.390391,0.133715,2.508511,1.159825,0.740178,0.649623,1.042542,1.148131
1,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),elasticnet,0.243307,0.071797,2.396853,0.182446,0.219425,0.014750,1.851956,0.180962,-0.122252,0.471687,2.664968,0.776426,0.337558,0.065963,2.153175,0.584176,0.365559,0.268115,0.471687,0.776426
2,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),extra_trees,0.879797,0.058299,0.929116,0.187140,0.085458,0.019408,0.692633,0.135063,0.493084,0.446675,1.728030,0.895053,0.218629,0.093130,1.354521,0.700489,0.386713,0.798914,0.446675,0.895053
3,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),gpr,0.994785,0.014223,0.072521,0.180366,0.006853,0.017123,0.051817,0.129585,0.525892,0.208691,1.740030,0.622594,0.219837,0.055734,1.373682,0.514996,0.468893,1.667509,0.208691,0.622594
4,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),gradient_boosting,0.756827,0.191917,1.256765,0.570049,0.115254,0.051855,0.932487,0.435018,0.340285,0.495693,1.906810,0.667955,0.250669,0.087728,1.475976,0.470863,0.416542,0.650045,0.495693,0.667955
5,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),lightgbm,0.960882,0.017741,0.523813,0.117612,0.048105,0.011329,0.369945,0.080881,0.755943,0.213604,1.119527,0.401198,0.149386,0.066139,0.846647,0.271502,0.204939,0.595714,0.213604,0.401198
6,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),linear_regression,0.246160,0.072058,2.392311,0.182941,0.219010,0.014807,1.812967,0.185283,-0.141316,0.528957,2.671702,0.796286,0.338675,0.073266,2.127950,0.586163,0.387477,0.279391,0.528957,0.796286
7,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),random_forest,0.784222,0.044020,1.270210,0.107989,0.116520,0.011760,0.892152,0.087986,0.365248,0.379903,1.983382,0.732653,0.251380,0.072291,1.519023,0.575792,0.418974,0.713172,0.379903,0.732653
8,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),ridge,0.245876,0.071986,2.392770,0.182871,0.219051,0.014797,1.826001,0.182784,-0.129702,0.507951,2.663187,0.787817,0.337495,0.070695,2.131934,0.583411,0.375578,0.270417,0.507951,0.787817
9,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),svr_rbf,0.515936,0.049674,1.916508,0.148339,0.175415,0.011453,1.247647,0.116575,0.189060,0.309094,2.301843,0.776993,0.287991,0.055776,1.767154,0.597772,0.326876,0.385334,0.309094,0.776993
10,pipeline1_single_original,Dataset_0136,single_output,Elongation (%),xgboost,0.954844,0.013501,0.576552,0.073590,0.052964,0.007967,0.459906,0.053263,0.642990,0.257581,1.408817,0.391650,0.187160,0.064389,1.126795,0.299539,0.311854,0.832265,0.257581,0.391650
11,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),ann,-0.563806,0.807684,6.699300,1.679011,0.318000,0.084156,5.557448,1.404223,-3.236696,3.803060,8.983173,2.843968,0.621595,0.262643,7.706804,2.744281,2.672890,2.283873,3.803060,2.843968
12,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),elasticnet,0.940412,0.008793,1.340604,0.072108,0.063692,0.006241,1.134469,0.077199,0.890525,0.079715,1.508191,0.354103,0.103926,0.035781,1.328791,0.346135,0.049887,0.167588,0.079715,0.354103
13,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),extra_trees,0.940137,0.015785,1.333160,0.129752,0.063526,0.009704,1.102856,0.108092,0.668815,0.205739,2.707772,0.574509,0.183194,0.047156,2.290770,0.569709,0.271322,1.374612,0.205739,0.574509
14,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),gpr,0.963041,0.009471,1.049163,0.101529,0.049954,0.007359,0.850328,0.087430,0.898811,0.079976,1.425535,0.310124,0.098679,0.034790,1.228239,0.333304,0.064229,0.376372,0.079976,0.310124
15,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),gradient_boosting,0.984684,0.008071,0.663181,0.150297,0.031575,0.008107,0.464555,0.086738,0.918096,0.064958,1.317755,0.387773,0.089664,0.032225,1.023023,0.313459,0.066588,0.654574,0.064958,0.387773
16,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),lightgbm,0.993236,0.002266,0.444334,0.068402,0.021177,0.004051,0.345235,0.053135,0.945300,0.039858,1.047991,0.205022,0.072744,0.024194,0.864229,0.195432,0.047935,0.603658,0.039858,0.205022
17,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),linear_regression,0.944199,0.008463,1.297185,0.074701,0.061627,0.006150,1.098334,0.076798,0.892273,0.080850,1.481720,0.331973,0.102367,0.035457,1.302544,0.328497,0.051926,0.184535,0.080850,0.331973
18,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),random_forest,0.927490,0.010189,1.478545,0.058814,0.070234,0.006318,1.222458,0.063553,0.739205,0.141143,2.458777,0.588997,0.163776,0.036732,2.119691,0.530366,0.188285,0.980232,0.141143,0.588997
19,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),ridge,0.943111,0.008542,1.309828,0.073799,0.062228,0.006168,1.111687,0.075478,0.892572,0.080142,1.484197,0.341251,0.102489,0.035701,1.309863,0.338125,0.050538,0.174368,0.080142,0.341251
20,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),svr_rbf,0.685587,0.030087,3.090402,0.193026,0.146177,0.005514,2.289094,0.120580,0.459151,0.200486,3.639871,0.943748,0.240331,0.044098,3.030140,0.786459,0.226437,0.549469,0.200486,0.943748
21,pipeline1_single_original,Dataset_0136,single_output,Hardness (HV),xgboost,0.994058,0.001731,0.418787,0.053236,0.019913,0.003128,0.325753,0.044296,0.939942,0.059359,1.060734,0.282900,0.074109,0.031119,0.804763,0.244479,0.054116,0.641947,0.059359,0.282900
22,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),ann,0.888572,0.065278,0.259899,0.069749,0.084714,0.024296,0.206228,0.057950,0.698050,0.225597,0.358954,0.087056,0.179686,0.060140,0.296181,0.079664,0.190522,0.099056,0.225597,0.087056
23,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),elasticnet,0.904232,0.010259,0.251263,0.014925,0.081471,0.008168,0.193007,0.011235,0.841864,0.086768,0.284673,0.127060,0.134353,0.040091,0.229312,0.088068,0.062368,0.033410,0.086768,0.127060
24,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),extra_trees,0.945116,0.009921,0.189554,0.015912,0.061490,0.007404,0.141530,0.011213,0.757563,0.117309,0.354843,0.145241,0.166958,0.043089,0.297038,0.113979,0.187553,0.165290,0.117309,0.145241
25,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),gpr,0.971479,0.020652,0.120518,0.067794,0.038730,0.022611,0.095916,0.054840,0.845019,0.112616,0.265916,0.098920,0.129515,0.046093,0.212786,0.066841,0.126460,0.145398,0.112616,0.098920
26,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),gradient_boosting,0.986089,0.008298,0.091193,0.025733,0.029890,0.009925,0.066003,0.017985,0.928459,0.046703,0.186374,0.078602,0.088440,0.028632,0.144951,0.058066,0.057630,0.095180,0.046703,0.078602
27,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),lightgbm,0.987374,0.002775,0.090769,0.010298,0.029391,0.003705,0.066498,0.005734,0.921288,0.055552,0.190657,0.104639,0.089510,0.034196,0.144237,0.070244,0.066086,0.099888,0.055552,0.104639
28,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),linear_regression,0.925429,0.008951,0.221917,0.017883,0.071784,0.006410,0.178508,0.013915,0.846613,0.094190,0.267275,0.073316,0.131323,0.037810,0.219511,0.062696,0.078816,0.045358,0.094190,0.073316
29,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),random_forest,0.934393,0.009577,0.207734,0.015055,0.067239,0.006043,0.151802,0.008130,0.792126,0.150666,0.318236,0.155491,0.149167,0.052831,0.257202,0.115335,0.142267,0.110503,0.150666,0.155491
30,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),ridge,0.924369,0.008975,0.223490,0.017825,0.072297,0.006450,0.179001,0.013505,0.851308,0.085453,0.266148,0.081882,0.129720,0.036350,0.219032,0.065125,0.073061,0.042658,0.085453,0.081882
31,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),svr_rbf,0.967338,0.013437,0.145011,0.029748,0.046494,0.007304,0.105062,0.010495,0.850916,0.113764,0.281683,0.163251,0.127933,0.046077,0.211867,0.102953,0.116422,0.136672,0.113764,0.163251
32,pipeline1_single_original,Dataset_0136,single_output,Si Particle Size (um),xgboost,0.991477,0.003487,0.072915,0.012596,0.023981,0.006412,0.055169,0.009856,0.936503,0.051558,0.171167,0.096098,0.079904,0.033734,0.129268,0.068329,0.054974,0.098253,0.051558,0.096098
33,pipeline1_single_original,Dataset_0136,single_output,Strain,ann,0.895533,0.034031,8.171977,1.372822,0.085511,0.015231,6.350698,1.213431,0.723835,0.216000,10.723108,3.823356,0.165557,0.070457,9.262674,3.183662,0.171698,2.551130,0.216000,3.823356
34,pipeline1_single_original,Dataset_0136,single_output,Strain,elasticnet,0.966126,0.003653,4.708710,0.265594,0.049178,0.002671,3.805081,0.254860,0.942628,0.031200,5.308556,1.064000,0.079883,0.020127,4.353587,0.945863,0.023497,0.599846,0.031200,1.064000
35,pipeline1_single_original,Dataset_0136,single_output,Strain,extra_trees,0.961398,0.007517,5.001823,0.333326,0.052314,0.004455,4.130131,0.253960,0.854595,0.107289,8.251102,2.405813,0.125026,0.045601,6.946541,2.037750,0.106804,3.249279,0.107289,2.405813
36,pipeline1_single_original,Dataset_0136,single_output,Strain,gpr,0.999405,0.000206,0.613733,0.099648,0.006428,0.001140,0.486941,0.091892,0.995478,0.002644,1.470655,0.368590,0.022331,0.007028,1.195909,0.316250,0.003927,0.856922,0.002644,0.368590
37,pipeline1_single_original,Dataset_0136,single_output,Strain,gradient_boosting,0.991043,0.011665,2.069313,1.243348,0.021615,0.013034,1.234973,0.563228,0.973110,0.020883,3.523175,1.484978,0.052080,0.020150,2.894388,1.256784,0.017933,1.453863,0.020883,1.484978
38,pipeline1_single_original,Dataset_0136,single_output,Strain,lightgbm,0.998554,0.000674,0.942708,0.190009,0.009879,0.002149,0.749185,0.153521,0.988552,0.008863,2.333258,0.993969,0.033998,0.011719,1.883566,0.823771,0.010002,1.390549,0.008863,0.993969
39,pipeline1_single_original,Dataset_0136,single_output,Strain,linear_regression,0.968645,0.003615,4.529865,0.282412,0.047306,0.002809,3.539461,0.284542,0.943533,0.036200,5.159327,1.177015,0.078208,0.024520,4.097365,0.895717,0.025112,0.629462,0.036200,1.177015
40,pipeline1_single_original,Dataset_0136,single_output,Strain,random_forest,0.946746,0.008858,5.881215,0.254587,0.061488,0.003844,4.649172,0.207076,0.828009,0.116366,9.018469,2.869850,0.135277,0.046330,7.553702,2.591810,0.118737,3.137254,0.116366,2.869850
41,pipeline1_single_original,Dataset_0136,single_output,Strain,ridge,0.967533,0.003631,4.609672,0.275277,0.048141,0.002749,3.691366,0.267853,0.943682,0.032035,5.226845,1.052286,0.078881,0.021231,4.233666,0.909157,0.023851,0.617174,0.032035,1.052286
42,pipeline1_single_original,Dataset_0136,single_output,Strain,svr_rbf,0.179378,0.037081,23.228601,1.246443,0.242490,0.010165,19.147063,1.165151,-0.089569,0.476875,24.204368,6.182174,0.353336,0.058187,21.220542,5.466820,0.268947,0.975767,0.476875,6.182174
43,pipeline1_single_original,Dataset_0136,single_output,Strain,xgboost,0.999116,0.000429,0.741377,0.148457,0.007762,0.001633,0.603808,0.111393,0.990390,0.007270,2.100767,0.734428,0.031570,0.011174,1.763716,0.599267,0.008726,1.359389,0.007270,0.734428
44,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),ann,-1.488719,0.842142,47.162171,7.903096,0.402623,0.068374,38.669624,7.231231,-4.039264,3.363449,56.796370,19.446974,0.699419,0.272186,48.498905,16.384346,2.550546,9.634199,3.363449,19.446974
45,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),elasticnet,0.946636,0.006892,6.952548,0.246699,0.059410,0.003328,6.245939,0.266833,0.914217,0.062713,7.658410,1.208200,0.094236,0.029636,6.993072,1.116744,0.032419,0.705862,0.062713,1.208200
46,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),extra_trees,0.958446,0.007553,6.125017,0.399508,0.052313,0.003823,5.174593,0.422795,0.844762,0.107098,10.136396,1.860385,0.126448,0.045581,8.741118,1.703079,0.113685,4.011379,0.107098,1.860385
47,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),gpr,0.998552,0.000589,1.121643,0.237432,0.009576,0.002075,0.845655,0.183845,0.991019,0.006602,2.433059,0.843652,0.029514,0.011382,1.919989,0.722392,0.007533,1.311416,0.006602,0.843652
48,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),gradient_boosting,0.993279,0.005614,2.251341,0.917738,0.019293,0.007949,1.481018,0.500767,0.980446,0.016392,3.698913,1.600970,0.043847,0.018047,3.114049,1.332297,0.012833,1.447572,0.016392,1.600970
49,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),lightgbm,0.998318,0.001258,1.154170,0.378056,0.009892,0.003341,0.913897,0.294058,0.988543,0.007627,2.877165,1.116503,0.034052,0.012495,2.476302,1.024329,0.009775,1.722995,0.007627,1.116503
50,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),linear_regression,0.949048,0.006751,6.792603,0.258764,0.058046,0.003386,6.251868,0.246953,0.914250,0.065390,7.547956,1.000852,0.093553,0.030408,7.034592,1.016041,0.034798,0.755353,0.065390,1.000852
51,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),random_forest,0.947030,0.007856,6.921078,0.217548,0.059148,0.003340,5.491589,0.216557,0.832476,0.109534,10.658400,2.692134,0.131167,0.046984,8.997308,2.627015,0.114553,3.737322,0.109534,2.692134
52,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),ridge,0.947966,0.006808,6.864885,0.253221,0.058662,0.003360,6.243815,0.255349,0.914888,0.063494,7.589071,1.101534,0.093650,0.029785,7.002589,1.053518,0.033078,0.724185,0.063494,1.101534
53,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),svr_rbf,0.113686,0.024547,28.469985,1.561507,0.242937,0.010742,22.164297,1.304581,-0.015908,0.249931,28.631454,6.928845,0.336700,0.056353,23.381512,5.679194,0.129594,0.161469,0.249931,6.928845
54,pipeline1_single_original,Dataset_0136,single_output,Temperature (°C),xgboost,0.999068,0.000319,0.904912,0.122478,0.007748,0.001217,0.726056,0.107212,0.991406,0.004269,2.520594,0.734421,0.030272,0.009012,2.156492,0.642343,0.007662,1.615682,0.004269,0.734421
55,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),ann,-0.176950,0.371245,16.945005,2.357946,0.283007,0.041589,13.888849,1.782436,-1.480359,1.448516,21.885534,5.904206,0.499245,0.162197,19.025673,5.868077,1.303409,4.940530,1.448516,5.904206
56,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),elasticnet,0.741836,0.042689,8.006330,0.582011,0.133801,0.013089,6.483339,0.510829,0.525352,0.549004,8.902675,2.177621,0.210110,0.099604,7.202942,1.554057,0.216484,0.896345,0.549004,2.177621
57,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),extra_trees,0.917492,0.016542,4.519465,0.423357,0.075360,0.006830,3.634407,0.413035,0.649345,0.339286,7.862853,1.559462,0.183612,0.074203,6.715018,1.369747,0.268147,3.343388,0.339286,1.559462
58,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),gpr,0.993525,0.005550,1.091239,0.664344,0.018184,0.011197,0.883568,0.550895,0.886909,0.115158,4.398085,1.064163,0.103128,0.045280,3.507762,0.903877,0.106616,3.306846,0.115158,1.064163
59,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),gradient_boosting,0.965346,0.017870,2.847338,0.729406,0.047747,0.013196,2.135921,0.606030,0.828760,0.169769,5.410014,1.756785,0.125484,0.057387,4.195883,1.014746,0.136586,2.562676,0.169769,1.756785
60,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),lightgbm,0.983182,0.006082,2.014149,0.370619,0.033658,0.006561,1.496083,0.233869,0.876345,0.164369,4.373000,1.504050,0.103339,0.057803,3.352230,1.074723,0.106837,2.358851,0.164369,1.504050
61,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),linear_regression,0.744005,0.042642,7.972155,0.585820,0.133231,0.013119,6.379639,0.521322,0.513749,0.594171,8.892323,2.308415,0.210758,0.105110,7.124867,1.537833,0.230255,0.920168,0.594171,2.308415
62,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),random_forest,0.906615,0.016220,4.814093,0.347512,0.080392,0.007089,3.840669,0.354728,0.685076,0.306677,7.388466,1.780025,0.172165,0.072617,6.249820,1.426978,0.221539,2.574372,0.306677,1.780025
63,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),ridge,0.743150,0.042654,7.985662,0.584267,0.133456,0.013106,6.444095,0.515305,0.522304,0.564035,8.887600,2.222026,0.210088,0.101507,7.172565,1.542271,0.220845,0.901939,0.564035,2.222026
64,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),svr_rbf,0.265014,0.021958,13.581846,0.533804,0.226567,0.010177,11.110227,0.528952,0.038435,0.241554,14.417621,2.787581,0.320635,0.043150,12.313619,2.618532,0.226579,0.835775,0.241554,2.787581
65,pipeline1_single_original,Dataset_0136,single_output,Ultimate Compression Strength (MPa),xgboost,0.988521,0.003066,1.678926,0.204936,0.028063,0.003974,1.287597,0.152200,0.906388,0.104230,3.936300,1.163887,0.092117,0.044382,3.104711,0.756561,0.082133,2.257374,0.104230,1.163887
66,pipeline1_single_original,Dataset_0136,single_output,wear rate,ann,0.613400,0.389251,0.536543,0.282140,0.133971,0.070522,0.402586,0.239987,-0.540380,1.842550,0.861605,0.382859,0.359787,0.221793,0.724760,0.329489,1.153780,0.325062,1.842550,0.382859
67,pipeline1_single_original,Dataset_0136,single_output,wear rate,elasticnet,0.909604,0.011731,0.288521,0.014093,0.071951,0.004773,0.218740,0.015033,0.860269,0.056406,0.319393,0.105036,0.120619,0.028550,0.255774,0.086374,0.049335,0.030872,0.056406,0.105036
68,pipeline1_single_original,Dataset_0136,single_output,wear rate,extra_trees,0.931556,0.013732,0.250421,0.023060,0.062445,0.006387,0.202042,0.016607,0.731647,0.127161,0.442105,0.121241,0.169052,0.044025,0.372384,0.109439,0.199909,0.191684,0.127161,0.121241
69,pipeline1_single_original,Dataset_0136,single_output,wear rate,gpr,0.961536,0.013496,0.182924,0.041733,0.045648,0.010858,0.154203,0.037302,0.884360,0.060956,0.278948,0.049121,0.109652,0.029583,0.241307,0.050831,0.077176,0.096025,0.060956,0.049121
70,pipeline1_single_original,Dataset_0136,single_output,wear rate,gradient_boosting,0.974870,0.030157,0.140506,0.062947,0.035142,0.016071,0.093642,0.051616,0.915115,0.093602,0.235884,0.100644,0.088806,0.035169,0.180181,0.084237,0.059755,0.095378,0.093602,0.100644
71,pipeline1_single_original,Dataset_0136,single_output,wear rate,lightgbm,0.987034,0.004326,0.107736,0.019405,0.026880,0.005073,0.074199,0.011521,0.941968,0.034180,0.204053,0.084408,0.075453,0.025299,0.146957,0.057612,0.045066,0.096317,0.034180,0.084408
72,pipeline1_single_original,Dataset_0136,single_output,wear rate,linear_regression,0.926866,0.009804,0.259589,0.016240,0.064725,0.004804,0.206090,0.014892,0.873363,0.057161,0.299956,0.065081,0.115429,0.025434,0.246554,0.066255,0.053503,0.040367,0.057161,0.065081
73,pipeline1_single_original,Dataset_0136,single_output,wear rate,random_forest,0.925446,0.007647,0.262296,0.010650,0.065359,0.002957,0.195354,0.011473,0.780624,0.088880,0.405515,0.124746,0.151724,0.030113,0.326515,0.096416,0.144823,0.143218,0.088880,0.124746

==========================================================================================
TOP-3 MODELS (selected from Pipeline 1, used in Pipelines 3 & 4): ['xgboost', 'gpr', 'lightgbm']
==========================================================================================

All pipeline results (fold-level + aggregated CSVs) saved to: C:\Users\mohammadhosein\Desktop\DeepLearning-miniProject\results
Combined summary saved to: C:\Users\mohammadhosein\Desktop\DeepLearning-miniProject\results\pipelines_summary.csv