# Experiment Tracking — MLflow (Phase 1 / MLOps)

Every model run in Pipelines 1 and 2 logs its parameters, per-fold-aggregated metrics (mean/std of R2, RMSE, NRMSE, MAE), the generalization gap, and the raw fold table as an artifact to a local SQLite-backed MLflow tracking store (`mlflow.db` at the repo root). This notebook queries that store directly (no retraining) and summarizes every experiment and run.

To browse runs interactively (with the plots/artifacts UI), launch:

```
mlflow ui --backend-store-uri sqlite:///mlflow.db
```

All summary tables produced here are saved to `results/mlflow/`, and the last cell shows the complete combined results.

Setup: point MLflow at the local SQLite store and configure pandas to display full tables.

In [1]:
import sys
from pathlib import Path

REPO_ROOT = Path.cwd().parent if (Path.cwd() / '..' / 'src').resolve().exists() else Path.cwd()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import mlflow
import pandas as pd
from mlflow.tracking import MlflowClient

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 300)

from src.config import PROJECT_ROOT, get_path
from src.utils.io import save_table

db_path = PROJECT_ROOT / 'mlflow.db'
mlflow.set_tracking_uri(f'sqlite:///{db_path.as_posix()}')
client = MlflowClient()
print('Tracking URI:', mlflow.get_tracking_uri())

Tracking URI: sqlite:///C:/Users/mohammadhosein/Desktop/DeepLearning-miniProject/mlflow.db

## Experiments overview

Every experiment corresponds to one `pipeline{1,2}_<dataset>` run (Pipelines 1 and 2 log to MLflow; Pipelines 3/4, tuning and XAI do not).

In [2]:
experiments = client.search_experiments()
overview = pd.DataFrame(
    [
        {
            'experiment_id': e.experiment_id,
            'experiment_name': e.name,
            'n_runs': len(client.search_runs([e.experiment_id])),
        }
        for e in experiments
    ]
).sort_values('experiment_name').reset_index(drop=True)
overview

   experiment_id         experiment_name  n_runs
0              0                 Default       0
1              1  pipeline1_Dataset_0136     154
2              2  pipeline1_Dataset_0172     110
3              3  pipeline1_Dataset_3772     110
4              4  pipeline2_Dataset_0136      22
5              5  pipeline2_Dataset_0172      22
6              6  pipeline2_Dataset_3772      22
7              7  pipeline3_Dataset_0136      42
8              8  pipeline3_Dataset_0172      30
9              9  pipeline3_Dataset_3772      30
10            10  pipeline4_Dataset_0136       6
11            11  pipeline4_Dataset_0172       6
12            12  pipeline4_Dataset_3772       6

## All runs, every experiment

`mlflow.search_runs` returns one row per run with every logged parameter and metric as a column.

In [3]:
all_runs = mlflow.search_runs(experiment_ids=[e.experiment_id for e in experiments], search_all_experiments=True)
print('Total logged runs:', len(all_runs))
all_runs

Total logged runs: 560

                               run_id experiment_id    status                                       artifact_uri                       start_time                         end_time  metrics.train_mae_std  metrics.test_r2_std  metrics.gap_r2  metrics.train_rmse_std  metrics.test_rmse_mean  \
0    b0f9688e3e4e486b992e71ea7e496b1b            12  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:54.434000+00:00 2026-07-18 21:44:54.920000+00:00               0.086508             0.194615        0.219680                0.363230                3.661759
1    7cb3131e463848eda1693828d843619a            12  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:48.425000+00:00 2026-07-18 21:44:48.828000+00:00               0.148067             0.107826        0.209728                0.302534                3.494039
2    72a33522e6ba46e48418e88d675b59ba            12  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:45.947000+00:00 2026-07-18 21:44:46.418000+00:00               0.074792             0.155423        0.197856                0.232943                3.464469
3    c788b3da1524435aaa3f540685e6dad8            11  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:34.296000+00:00 2026-07-18 21:44:34.739000+00:00               0.053485             0.026448        0.068730                0.143667                2.631003
4    ce3c3e07e9cf4e9d9baa0492551dec61            11  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:27.236000+00:00 2026-07-18 21:44:27.656000+00:00               0.081697             0.044612        0.113534                0.170365                2.888986
5    d569127de58446e6b094f0c72cefd8c4            11  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:23.988000+00:00 2026-07-18 21:44:24.476000+00:00               0.054673             0.024416        0.058853                0.160005                2.648487
6    c3247d41699340b7957cdc29ff32d415            10  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:12.006000+00:00 2026-07-18 21:44:12.427000+00:00               0.067925             0.040665        0.070091                0.119463                2.332151
7    20f8a4cb7a4d464cbcdba50fded98e78            10  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:02.872000+00:00 2026-07-18 21:44:03.276000+00:00               0.213521             0.050161        0.122631                0.332392                3.322324
8    7a7d805a07a14729a8e597ea83995bb4            10  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:00.703000+00:00 2026-07-18 21:44:00.934000+00:00               0.036046             0.042894        0.080704                0.067778                2.098213
9    f46fba3d6ade4f55b64631dc006d84a0             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:44.302000+00:00 2026-07-18 21:43:44.790000+00:00               0.115874             0.384694        0.423497                0.142131                1.884728
10   8ee6701a336741cd94f06a9c5df27939             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:42.567000+00:00 2026-07-18 21:43:42.948000+00:00               0.300459             0.238438        0.560018                0.405451                2.379263
11   9308505909884673ba204e9c6b96f70e             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:39.258000+00:00 2026-07-18 21:43:39.718000+00:00               0.087323             0.291668        0.404763                0.113182                1.906369
12   4960f67ff225479eb3bfd22c6d2b9352             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:36.257000+00:00 2026-07-18 21:43:36.687000+00:00               0.417217             0.736341        0.378901                0.862396                7.623921
13   f168d1a001cb4df4a3cc8aaad0ac13cb             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:34.476000+00:00 2026-07-18 21:43:34.854000+00:00               0.878895             0.437074        0.316212                1.132377                7.448087
14   13edcfafd21e4fa388adcdea70875587             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:30.945000+00:00 2026-07-18 21:43:31.410000+00:00               0.364188             0.610912        0.330541                0.557381                7.231387
15   b7774801fbde4a308802a13fcdf9e540             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:28.017000+00:00 2026-07-18 21:43:28.470000+00:00               0.006492             0.056940        0.070083                0.008949                0.174906
16   1bb7801b72a2410e88a7a77fc4fe4a21             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:26.375000+00:00 2026-07-18 21:43:26.762000+00:00               0.008301             0.049297        0.052126                0.009565                0.163253
17   736d29b5d02e444b9d1747ce27353ee5             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:23.381000+00:00 2026-07-18 21:43:23.865000+00:00               0.007330             0.089009        0.065816                0.008171                0.152914
18   d34f3aa9a2b843288d1a0a70041dc86e             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:20.468000+00:00 2026-07-18 21:43:20.908000+00:00               0.139220             0.241897        0.151640                0.215836                1.828338
19   fff90e91ae0543088bd8b0586b484dde             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:18.664000+00:00 2026-07-18 21:43:19.098000+00:00               0.239595             0.260549        0.162941                0.317742                1.824911
20   08a551de0e9248f69db920ff9cb7e0b9             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:15.403000+00:00 2026-07-18 21:43:15.883000+00:00               0.101418             0.201732        0.130346                0.141979                1.655039
21   50085dc326b84bab9231118512d7febb             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:12.463000+00:00 2026-07-18 21:43:12.944000+00:00               0.003202             0.048266        0.074281                0.003464                0.056510
22   cd7fb2cb9d604dc2ae7d48fa54d589e0             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:10.902000+00:00 2026-07-18 21:43:11.304000+00:00               0.010166             0.058747        0.055637                0.014892                0.050330
23   995f358ba3e04d739a10526fe89a4570             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:08.011000+00:00 2026-07-18 21:43:08.427000+00:00               0.002621             0.050311        0.057816                0.003097                0.050198
24   8fbc5ed8bd3345a686a936a632bac68f             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:05.205000+00:00 2026-07-18 21:43:05.698000+00:00               0.061563             0.100348        0.163035                0.076868                1.335207
25   a87157e940ee432789d7a5cd27a43cb4             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:03.492000+00:00 2026-07-18 21:43:03.890000+00:00               0.233984             0.222904        0.464924                0.322508                2.176189
26   1effd95130f442ce8990faed96cf10de             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:00.116000+00:00 2026-07-18 21:43:00.513000+00:00               0.054491             0.101944        0.153793                0.063915                1.361788
27   40e99885accd4be79b744c58a42b0ff5             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:57.170000+00:00 2026-07-18 21:42:57.629000+00:00               0.237583             0.059171        0.092799                0.352704                5.520350
28   fd7ba97cac3a454c9e6d74051a3ae721             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:55.125000+00:00 2026-07-18 21:42:55.517000+00:00               0.290428             0.064927        0.103848                0.410597                5.854225
29   84ec2f2626d44c2e876dbb2a574b386d             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:52.330000+00:00 2026-07-18 21:42:52.806000+00:00               0.218058             0.057481        0.079565                0.370948                5.588709
30   7c97c88ff9764b60ae412d41507db4d8             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:49.278000+00:00 2026-07-18 21:42:49.733000+00:00               0.005529             0.009290        0.015086                0.007554                0.183951
31   b972639ac3954914a0ff50ce53374c7e             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:47.561000+00:00 2026-07-18 21:42:47.978000+00:00               0.006845             0.006143        0.009866                0.006987                0.194588
32   ab1e3d2cd1cb466d953acb187e624763             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:44.678000+00:00 2026-07-18 21:42:45.147000+00:00               0.005464             0.005073        0.007733                0.005942                0.146739
33   329083b8eb4e422ba140cc930dc72306             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:41.720000+00:00 2026-07-18 21:42:42.194000+00:00               0.061639             0.032807        0.049253                0.099201                1.373056
34   1478e05c9c104201ab39a52cc7f2f7b5             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:39.823000+00:00 2026-07-18 21:42:40.228000+00:00               0.103768             0.058518        0.051474                0.144059                1.493015
35   6e91fc61ea8742599c47b9206b732a25             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:37.061000+00:00 2026-07-18 21:42:37.489000+00:00               0.068456             0.029015        0.038532                0.098058                1.266839
36   f382bcc68f314d15affc0db86ec3db11             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:34.061000+00:00 2026-07-18 21:42:34.492000+00:00               0.006747             0.018058        0.023475                0.009472                0.146138
37   740b17f4357649839040f2cae8a4020e             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:32.432000+00:00 2026-07-18 21:42:32.818000+00:00               0.021629             0.013028        0.019590                0.031652                0.146321
38   279bdfe13b594efabd6e64ce4c6a65a0             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:29.602000+00:00 2026-07-18 21:42:30.001000+00:00               0.004470             0.008628        0.014642                0.007225                0.130322
39   e715806c2a844161940684fd407bdc04             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:26.694000+00:00 2026-07-18 21:42:27.144000+00:00               0.153521             0.008863        0.010002                0.190009                2.333258
40   d16e9c985f534bd3877a4c95daa5418a             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:24.885000+00:00 2026-07-18 21:42:25.278000+00:00               0.174537             0.006762        0.009570                0.228336                2.319261
41   303f20dea5854c39816109a8e7a18096             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:22.071000+00:00 2026-07-18 21:42:22.527000+00:00               0.111393             0.007270        0.008726                0.148457                2.100767
42   b2e197e932ee4854a2c97db953889a8f             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:18.956000+00:00 2026-07-18 21:42:19.473000+00:00               0.294058             0.007627        0.009775                0.378056                2.877165
43   ef393cf619ba4a6fbc96aeeaf5c35365             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:17.192000+00:00 2026-07-18 21:42:17.576000+00:00               0.154103             0.007818        0.010140                0.135044                3.129273
44   993d20596ef84933b7a87d7fb2611694             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:14.334000+00:00 2026-07-18 21:42:14.877000+00:00               0.107212             0.004269        0.007662                0.122478                2.520594
45   e05a81c9d8514f0892d4a6e7126b9f7a             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:11.388000+00:00 2026-07-18 21:42:11.869000+00:00               0.080881             0.213604        0.204939                0.117612                1.119527
46   8258a431287a47d191355f3c0e0c5e7e             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:09.624000+00:00 2026-07-18 21:42:10.004000+00:00               0.255015             0.237686        0.522750                0.369541                1.898647
47   372cf86eb8cd4cb5a4709ef79ae3c85a             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:06.105000+00:00 2026-07-18 21:42:06.595000+00:00               0.053263             0.257581        0.311854                0.073590                1.408817
48   85dc35d252254c3481ff0945b62528b7             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:03.060000+00:00 2026-07-18 21:42:03.521000+00:00               0.233869             0.164369        0.106837                0.370619                4.373000
49   cbce2681bd944fe6bc423b6c7bd88bb1             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:01.240000+00:00 2026-07-18 21:42:01.637000+00:00               0.529056             0.118536        0.103852                0.638025                4.280934
50   21812dc6da8c40f4a5623fff7c83d3b4             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:57.748000+00:00 2026-07-18 21:41:58.212000+00:00               0.152200             0.104230        0.082133                0.204936                3.936300
51   28adaf492cd44268a29f19b4d7c6ef44             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:54.767000+00:00 2026-07-18 21:41:55.309000+00:00               0.011521             0.034180        0.045066                0.019405                0.204053
52   300fbbb0da6945e7a83878ed7826f203             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:52.999000+00:00 2026-07-18 21:41:53.390000+00:00               0.039256             0.036616        0.063641                0.046184                0.241431
53   f686510cfadf4048b77ab7b077aa5f09             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:50.050000+00:00 2026-07-18 21:41:50.502000+00:00               0.009929             0.033836        0.045466                0.012391                0.189381
54   d1a219c7ecf449198119563a4fdd4597             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:47.092000+00:00 2026-07-18 21:41:47.578000+00:00               0.053135             0.039858        0.047935                0.068402                1.047991
55   60dbfb63b5a243b5bc86b6e613ff600b             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:45.264000+00:00 2026-07-18 21:41:45.687000+00:00               0.074890             0.054947        0.048654                0.092597                1.216244
56   41a07ad373b4459d8d8ca503f5b81ab0             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:42.384000+00:00 2026-07-18 21:41:42.836000+00:00               0.044296             0.059359        0.054116                0.053236                1.060734
57   9df89a67d6ef46169d1ddc9188f3f620             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:39.366000+00:00 2026-07-18 21:41:39.847000+00:00               0.005734             0.055552        0.066086                0.010298                0.190657
58   bee8d020da454107a09878669d05a84b             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:37.621000+00:00 2026-07-18 21:41:38.029000+00:00               0.034616             0.089865        0.093578                0.045301                0.225994
59   91efead6ba3e430da6d494201ebc2f2a             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:34.637000+00:00 2026-07-18 21:41:35.171000+00:00               0.009856             0.051558        0.054974                0.012596                0.171167
60   b7df61b9c99149278ff3d1ba73eb4545             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:31.609000+00:00 2026-07-18 21:41:32.065000+00:00               0.086508             0.194615        0.219680                0.363230                3.661759
61   d975c122a0ee4d24824af22622dbb0d1             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:25.473000+00:00 2026-07-18 21:41:25.871000+00:00               0.919412             1.204500        1.262269                1.620947               11.161792
62   636cf48830fd4ed09650030aa7df6a13             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:40:32.941000+00:00 2026-07-18 21:40:33.341000+00:00               0.074792             0.155423        0.197856                0.232943                3.464469
63   966afa4ee8c04a79bb4cfb861b03dbae             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:40:21.040000+00:00 2026-07-18 21:40:21.434000+00:00               0.181404             0.158628        0.188753                0.392117                3.816380
64   c7601a936de24e5786c03ba797fbcd3a             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:40:12.234000+00:00 2026-07-18 21:40:12.626000+00:00               0.112142             0.211249        0.414408                0.184381                4.982067
65   173542ec3b784a65a72b6900765dddf3             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:40:04.764000+00:00 2026-07-18 21:40:04.980000+00:00               0.069248             0.188431        0.292381                0.152518                4.803601
66   972ce13a7dfb4a0c818cd140a5c66635             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:39:54.993000+00:00 2026-07-18 21:39:55.381000+00:00               0.186742             0.119628        0.228981                0.363942                3.602656
67   3008e7e28f2a4f02abb46d61bc188c60             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:39:52.516000+00:00 2026-07-18 21:39:52.936000+00:00               0.169477             0.093442        0.192406                0.310366                7.331517

## Best run per experiment (by mean test R2)

In [4]:
if 'metrics.test_r2_mean' in all_runs.columns:
    best_per_experiment = (
        all_runs.sort_values('metrics.test_r2_mean', ascending=False)
        .groupby('experiment_id', as_index=False)
        .first()
    )
    key_cols = [
        c for c in best_per_experiment.columns
        if c in ('experiment_id', 'run_id', 'tags.mlflow.runName', 'status')
        or c.startswith('params.') or c.startswith('metrics.')
    ]
    best_per_experiment = best_per_experiment.merge(
        overview[['experiment_id', 'experiment_name']], on='experiment_id'
    )
    display_cols = ['experiment_name'] + [c for c in key_cols if c != 'experiment_id']
    display(best_per_experiment[display_cols])
else:
    print('No runs with metrics.test_r2_mean found yet — run notebook 02 first.')
    best_per_experiment = pd.DataFrame()
    display_cols = []

,experiment_name,run_id,status,metrics.train_mae_std,metrics.test_r2_std,metrics.gap_r2,metrics.train_rmse_std,metrics.test_rmse_mean,metrics.test_mae_mean,metrics.train_rmse_mean,metrics.train_nrmse_mean,metrics.train_mae_mean,metrics.gap_rmse,metrics.train_r2_std,metrics.test_nrmse_std,metrics.train_r2_mean,metrics.test_nrmse_mean,metrics.test_rmse_std,metrics.test_r2_mean,metrics.train_nrmse_std,metrics.test_mae_std,params.discrete,params.model,params.mode,params.targets,params.dataset,params.target,tags.mlflow.runName
0,pipeline1_Dataset_0136,4eb3fadfe0fa466299eb959f67642603,FINISHED,0.091892,0.002644,0.003927,0.099648,1.470655,1.195909,0.613733,0.006428,0.486941,0.856922,0.000206,0.007028,0.999405,0.022331,0.368590,0.995478,0.001140,0.316250,False,gpr,single_output,None,Dataset_0136,Strain,gpr__Strain
1,pipeline4_Dataset_0136,c3247d41699340b7957cdc29ff32d415,FINISHED,0.067925,0.040665,0.070091,0.119463,2.332151,1.387738,0.999666,0.002336,0.573578,1.332485,0.002575,0.001186,0.986940,0.005690,0.507603,0.916849,0.000279,0.248628,True,lightgbm,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_0136,None,lightgbm__multi
2,pipeline4_Dataset_0172,d569127de58446e6b094f0c72cefd8c4,FINISHED,0.054673,0.024416,0.058853,0.160005,2.648487,1.231394,1.454139,0.007980,0.677201,1.194348,0.003122,0.003563,0.977683,0.015247,0.647393,0.918830,0.000911,0.215759,True,xgboost,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_0172,None,xgboost__multi
3,pipeline4_Dataset_3772,80dcf225f9ee4008b9c43407603a8166,FINISHED,0.074792,0.155423,0.197856,0.232943,3.464469,1.689501,1.427529,0.007841,0.701445,2.036940,0.004768,0.006268,0.970795,0.020036,1.017304,0.772938,0.001344,0.394142,True,xgboost,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_3772,None,xgboost__multi
4,pipeline1_Dataset_0172,92223c0543ad4087b0d34681d9be7ab6,FINISHED,0.005464,0.005073,0.007733,0.005942,0.146739,0.110221,0.089248,0.015201,0.067008,0.057492,0.000442,0.006172,0.996152,0.030715,0.041609,0.988418,0.001120,0.024934,False,xgboost,single_output,None,Dataset_0172,wear rate,xgboost__wear rate
5,pipeline1_Dataset_3772,043574f85f604a0488fe6015674f1680,FINISHED,0.002621,0.050311,0.057816,0.003097,0.050198,0.039668,0.026183,0.034563,0.019312,0.024015,0.004513,0.032863,0.983774,0.090063,0.025224,0.925959,0.005963,0.018491,False,xgboost,single_output,None,Dataset_3772,Si Particle Size (um),xgboost__Si Particle Size (um)
6,pipeline2_Dataset_0136,98eacf5ad3d44f67ba6d4c4c9aca9a09,FINISHED,0.067925,0.040665,0.070091,0.119463,2.332151,1.387738,0.999666,0.002336,0.573578,1.332485,0.002575,0.001186,0.986940,0.005690,0.507603,0.916849,0.000279,0.248628,False,lightgbm,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_0136,None,lightgbm__multi
7,pipeline2_Dataset_0172,97ae7299bf2e4730b20940be813e9386,FINISHED,0.054673,0.024416,0.058853,0.160005,2.648487,1.231394,1.454139,0.007980,0.677201,1.194348,0.003122,0.003563,0.977683,0.015247,0.647393,0.918830,0.000911,0.215759,False,xgboost,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_0172,None,xgboost__multi
8,pipeline2_Dataset_3772,636cf48830fd4ed09650030aa7df6a13,FINISHED,0.074792,0.155423,0.197856,0.232943,3.464469,1.689501,1.427529,0.007841,0.701445,2.036940,0.004768,0.006268,0.970795,0.020036,1.017304,0.772938,0.001344,0.394142,False,xgboost,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_3772,None,xgboost__multi
9,pipeline3_Dataset_0136,153223baea114afdb58a9171747082af,FINISHED,0.107212,0.004269,0.007662,0.122478,2.520594,2.156492,0.904912,0.007748,0.726056,1.615682,0.000319,0.009012,0.999068,0.030272,0.734421,0.991406,0.001217,0.642343,True,xgboost,single_output,None,Dataset_0136,Temperature (°C),xgboost__Temperature (°C)
10,pipeline3_Dataset_0172,ab1e3d2cd1cb466d953acb187e624763,FINISHED,0.005464,0.005073,0.007733,0.005942,0.146739,0.110221,0.089248,0.015201,0.067008,0.057492,0.000442,0.006172,0.996152,0.030715,0.041609,0.988418,0.001120,0.024934,True,xgboost,single_output,None,Dataset_0172,wear rate,xgboost__wear rate
11,pipeline3_Dataset_3772,995f358ba3e04d739a10526fe89a4570,FINISHED,0.002621,0.050311,0.057816,0.003097,0.050198,0.039668,0.026183,0.034563,0.019312,0.024015,0.004513,0.032863,0.983774,0.090063,0.025224,0.925959,0.005963,0.018491,True,xgboost,single_output,None,Dataset_3772,Si Particle Size (um),xgboost__Si Particle Size (um)

## Top 15 runs overall (by mean test R2)

In [5]:
if not all_runs.empty and 'metrics.test_r2_mean' in all_runs.columns:
    metric_cols = [c for c in all_runs.columns if c.startswith('metrics.')]
    param_cols = [c for c in all_runs.columns if c.startswith('params.')]
    top_runs = all_runs.sort_values('metrics.test_r2_mean', ascending=False).head(15)
    display(top_runs[['experiment_id', 'tags.mlflow.runName'] + param_cols + metric_cols])
else:
    top_runs = pd.DataFrame()
    print('No runs available yet.')

,experiment_id,tags.mlflow.runName,params.discrete,params.model,params.mode,params.targets,params.dataset,params.target,metrics.train_mae_std,metrics.test_r2_std,metrics.gap_r2,metrics.train_rmse_std,metrics.test_rmse_mean,metrics.test_mae_mean,metrics.train_rmse_mean,metrics.train_nrmse_mean,metrics.train_mae_mean,metrics.gap_rmse,metrics.train_r2_std,metrics.test_nrmse_std,metrics.train_r2_mean,metrics.test_nrmse_mean,metrics.test_rmse_std,metrics.test_r2_mean,metrics.train_nrmse_std,metrics.test_mae_std
209,1,gpr__Strain,False,gpr,single_output,None,Dataset_0136,Strain,0.091892,0.002644,0.003927,0.099648,1.470655,1.195909,0.613733,0.006428,0.486941,0.856922,0.000206,0.007028,0.999405,0.022331,0.368590,0.995478,0.001140,0.316250
489,1,gpr__Strain,False,gpr,single_output,None,Dataset_0136,Strain,0.091892,0.002644,0.003927,0.099648,1.470655,1.195909,0.613733,0.006428,0.486941,0.856922,0.000206,0.007028,0.999405,0.022331,0.368590,0.995478,0.001140,0.316250
324,7,xgboost__Temperature (°C),True,xgboost,single_output,None,Dataset_0136,Temperature (°C),0.107212,0.004269,0.007662,0.122478,2.520594,2.156492,0.904912,0.007748,0.726056,1.615682,0.000319,0.009012,0.999068,0.030272,0.734421,0.991406,0.001217,0.642343
216,1,xgboost__Temperature (°C),False,xgboost,single_output,None,Dataset_0136,Temperature (°C),0.107212,0.004269,0.007662,0.122478,2.520594,2.156492,0.904912,0.007748,0.726056,1.615682,0.000319,0.009012,0.999068,0.030272,0.734421,0.991406,0.001217,0.642343
44,7,xgboost__Temperature (°C),True,xgboost,single_output,None,Dataset_0136,Temperature (°C),0.107212,0.004269,0.007662,0.122478,2.520594,2.156492,0.904912,0.007748,0.726056,1.615682,0.000319,0.009012,0.999068,0.030272,0.734421,0.991406,0.001217,0.642343
496,1,xgboost__Temperature (°C),False,xgboost,single_output,None,Dataset_0136,Temperature (°C),0.107212,0.004269,0.007662,0.122478,2.520594,2.156492,0.904912,0.007748,0.726056,1.615682,0.000319,0.009012,0.999068,0.030272,0.734421,0.991406,0.001217,0.642343
500,1,gpr__Temperature (°C),False,gpr,single_output,None,Dataset_0136,Temperature (°C),0.183845,0.006602,0.007533,0.237432,2.433059,1.919989,1.121643,0.009576,0.845655,1.311416,0.000589,0.011382,0.998552,0.029514,0.843652,0.991019,0.002075,0.722392
220,1,gpr__Temperature (°C),False,gpr,single_output,None,Dataset_0136,Temperature (°C),0.183845,0.006602,0.007533,0.237432,2.433059,1.919989,1.121643,0.009576,0.845655,1.311416,0.000589,0.011382,0.998552,0.029514,0.843652,0.991019,0.002075,0.722392
205,1,xgboost__Strain,False,xgboost,single_output,None,Dataset_0136,Strain,0.111393,0.007270,0.008726,0.148457,2.100767,1.763716,0.741377,0.007762,0.603808,1.359389,0.000429,0.011174,0.999116,0.031570,0.734428,0.990390,0.001633,0.599267
41,7,xgboost__Strain,True,xgboost,single_output,None,Dataset_0136,Strain,0.111393,0.007270,0.008726,0.148457,2.100767,1.763716,0.741377,0.007762,0.603808,1.359389,0.000429,0.011174,0.999116,0.031570,0.734428,0.990390,0.001633,0.599267
485,1,xgboost__Strain,False,xgboost,single_output,None,Dataset_0136,Strain,0.111393,0.007270,0.008726,0.148457,2.100767,1.763716,0.741377,0.007762,0.603808,1.359389,0.000429,0.011174,0.999116,0.031570,0.734428,0.990390,0.001633,0.599267
321,7,xgboost__Strain,True,xgboost,single_output,None,Dataset_0136,Strain,0.111393,0.007270,0.008726,0.148457,2.100767,1.763716,0.741377,0.007762,0.603808,1.359389,0.000429,0.011174,0.999116,0.031570,0.734428,0.990390,0.001633,0.599267
39,7,lightgbm__Strain,True,lightgbm,single_output,None,Dataset_0136,Strain,0.153521,0.008863,0.010002,0.190009,2.333258,1.883566,0.942708,0.009879,0.749185,1.390549,0.000674,0.011719,0.998554,0.033998,0.993969,0.988552,0.002149,0.823771
483,1,lightgbm__Strain,False,lightgbm,single_output,None,Dataset_0136,Strain,0.153521,0.008863,0.010002,0.190009,2.333258,1.883566,0.942708,0.009879,0.749185,1.390549,0.000674,0.011719,0.998554,0.033998,0.993969,0.988552,0.002149,0.823771
319,7,lightgbm__Strain,True,lightgbm,single_output,None,Dataset_0136,Strain,0.153521,0.008863,0.010002,0.190009,2.333258,1.883566,0.942708,0.009879,0.749185,1.390549,0.000674,0.011719,0.998554,0.033998,0.993969,0.988552,0.002149,0.823771

## Final Summary — Complete MLflow Tracking Overview

Experiments overview, every run, and the best run per experiment, saved to `results/mlflow/`.

In [6]:
mlflow_out_dir = get_path('results_dir') / 'mlflow'
save_table(overview, mlflow_out_dir / 'experiments_overview.csv')
save_table(all_runs, mlflow_out_dir / 'all_runs.csv')
if not best_per_experiment.empty:
    save_table(best_per_experiment, mlflow_out_dir / 'best_run_per_experiment.csv')

print('=' * 90)
print('1) EXPERIMENTS OVERVIEW')
print('=' * 90)
display(overview)

print()
print('=' * 90)
print(f'2) ALL {len(all_runs)} LOGGED RUNS')
print('=' * 90)
display(all_runs)

if not best_per_experiment.empty:
    print()
    print('=' * 90)
    print('3) BEST RUN PER EXPERIMENT (highest mean test R2)')
    print('=' * 90)
    display(best_per_experiment[display_cols])

print()
print('MLflow tracking store:', db_path.resolve())
print('Launch the UI with: mlflow ui --backend-store-uri sqlite:///mlflow.db')
print('Summary tables saved to:', mlflow_out_dir.resolve())

==========================================================================================
1) EXPERIMENTS OVERVIEW
==========================================================================================

   experiment_id         experiment_name  n_runs
0              0                 Default       0
1              1  pipeline1_Dataset_0136     154
2              2  pipeline1_Dataset_0172     110
3              3  pipeline1_Dataset_3772     110
4              4  pipeline2_Dataset_0136      22
5              5  pipeline2_Dataset_0172      22
6              6  pipeline2_Dataset_3772      22
7              7  pipeline3_Dataset_0136      42
8              8  pipeline3_Dataset_0172      30
9              9  pipeline3_Dataset_3772      30
10            10  pipeline4_Dataset_0136       6
11            11  pipeline4_Dataset_0172       6
12            12  pipeline4_Dataset_3772       6

==========================================================================================
2) ALL 560 LOGGED RUNS
==========================================================================================

                               run_id experiment_id    status                                       artifact_uri                       start_time                         end_time  metrics.train_mae_std  metrics.test_r2_std  metrics.gap_r2  metrics.train_rmse_std  metrics.test_rmse_mean  \
0    b0f9688e3e4e486b992e71ea7e496b1b            12  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:54.434000+00:00 2026-07-18 21:44:54.920000+00:00               0.086508             0.194615        0.219680                0.363230                3.661759
1    7cb3131e463848eda1693828d843619a            12  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:48.425000+00:00 2026-07-18 21:44:48.828000+00:00               0.148067             0.107826        0.209728                0.302534                3.494039
2    72a33522e6ba46e48418e88d675b59ba            12  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:45.947000+00:00 2026-07-18 21:44:46.418000+00:00               0.074792             0.155423        0.197856                0.232943                3.464469
3    c788b3da1524435aaa3f540685e6dad8            11  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:34.296000+00:00 2026-07-18 21:44:34.739000+00:00               0.053485             0.026448        0.068730                0.143667                2.631003
4    ce3c3e07e9cf4e9d9baa0492551dec61            11  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:27.236000+00:00 2026-07-18 21:44:27.656000+00:00               0.081697             0.044612        0.113534                0.170365                2.888986
5    d569127de58446e6b094f0c72cefd8c4            11  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:23.988000+00:00 2026-07-18 21:44:24.476000+00:00               0.054673             0.024416        0.058853                0.160005                2.648487
6    c3247d41699340b7957cdc29ff32d415            10  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:12.006000+00:00 2026-07-18 21:44:12.427000+00:00               0.067925             0.040665        0.070091                0.119463                2.332151
7    20f8a4cb7a4d464cbcdba50fded98e78            10  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:02.872000+00:00 2026-07-18 21:44:03.276000+00:00               0.213521             0.050161        0.122631                0.332392                3.322324
8    7a7d805a07a14729a8e597ea83995bb4            10  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:44:00.703000+00:00 2026-07-18 21:44:00.934000+00:00               0.036046             0.042894        0.080704                0.067778                2.098213
9    f46fba3d6ade4f55b64631dc006d84a0             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:44.302000+00:00 2026-07-18 21:43:44.790000+00:00               0.115874             0.384694        0.423497                0.142131                1.884728
10   8ee6701a336741cd94f06a9c5df27939             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:42.567000+00:00 2026-07-18 21:43:42.948000+00:00               0.300459             0.238438        0.560018                0.405451                2.379263
11   9308505909884673ba204e9c6b96f70e             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:39.258000+00:00 2026-07-18 21:43:39.718000+00:00               0.087323             0.291668        0.404763                0.113182                1.906369
12   4960f67ff225479eb3bfd22c6d2b9352             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:36.257000+00:00 2026-07-18 21:43:36.687000+00:00               0.417217             0.736341        0.378901                0.862396                7.623921
13   f168d1a001cb4df4a3cc8aaad0ac13cb             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:34.476000+00:00 2026-07-18 21:43:34.854000+00:00               0.878895             0.437074        0.316212                1.132377                7.448087
14   13edcfafd21e4fa388adcdea70875587             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:30.945000+00:00 2026-07-18 21:43:31.410000+00:00               0.364188             0.610912        0.330541                0.557381                7.231387
15   b7774801fbde4a308802a13fcdf9e540             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:28.017000+00:00 2026-07-18 21:43:28.470000+00:00               0.006492             0.056940        0.070083                0.008949                0.174906
16   1bb7801b72a2410e88a7a77fc4fe4a21             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:26.375000+00:00 2026-07-18 21:43:26.762000+00:00               0.008301             0.049297        0.052126                0.009565                0.163253
17   736d29b5d02e444b9d1747ce27353ee5             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:23.381000+00:00 2026-07-18 21:43:23.865000+00:00               0.007330             0.089009        0.065816                0.008171                0.152914
18   d34f3aa9a2b843288d1a0a70041dc86e             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:20.468000+00:00 2026-07-18 21:43:20.908000+00:00               0.139220             0.241897        0.151640                0.215836                1.828338
19   fff90e91ae0543088bd8b0586b484dde             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:18.664000+00:00 2026-07-18 21:43:19.098000+00:00               0.239595             0.260549        0.162941                0.317742                1.824911
20   08a551de0e9248f69db920ff9cb7e0b9             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:15.403000+00:00 2026-07-18 21:43:15.883000+00:00               0.101418             0.201732        0.130346                0.141979                1.655039
21   50085dc326b84bab9231118512d7febb             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:12.463000+00:00 2026-07-18 21:43:12.944000+00:00               0.003202             0.048266        0.074281                0.003464                0.056510
22   cd7fb2cb9d604dc2ae7d48fa54d589e0             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:10.902000+00:00 2026-07-18 21:43:11.304000+00:00               0.010166             0.058747        0.055637                0.014892                0.050330
23   995f358ba3e04d739a10526fe89a4570             9  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:08.011000+00:00 2026-07-18 21:43:08.427000+00:00               0.002621             0.050311        0.057816                0.003097                0.050198
24   8fbc5ed8bd3345a686a936a632bac68f             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:05.205000+00:00 2026-07-18 21:43:05.698000+00:00               0.061563             0.100348        0.163035                0.076868                1.335207
25   a87157e940ee432789d7a5cd27a43cb4             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:03.492000+00:00 2026-07-18 21:43:03.890000+00:00               0.233984             0.222904        0.464924                0.322508                2.176189
26   1effd95130f442ce8990faed96cf10de             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:43:00.116000+00:00 2026-07-18 21:43:00.513000+00:00               0.054491             0.101944        0.153793                0.063915                1.361788
27   40e99885accd4be79b744c58a42b0ff5             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:57.170000+00:00 2026-07-18 21:42:57.629000+00:00               0.237583             0.059171        0.092799                0.352704                5.520350
28   fd7ba97cac3a454c9e6d74051a3ae721             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:55.125000+00:00 2026-07-18 21:42:55.517000+00:00               0.290428             0.064927        0.103848                0.410597                5.854225
29   84ec2f2626d44c2e876dbb2a574b386d             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:52.330000+00:00 2026-07-18 21:42:52.806000+00:00               0.218058             0.057481        0.079565                0.370948                5.588709
30   7c97c88ff9764b60ae412d41507db4d8             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:49.278000+00:00 2026-07-18 21:42:49.733000+00:00               0.005529             0.009290        0.015086                0.007554                0.183951
31   b972639ac3954914a0ff50ce53374c7e             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:47.561000+00:00 2026-07-18 21:42:47.978000+00:00               0.006845             0.006143        0.009866                0.006987                0.194588
32   ab1e3d2cd1cb466d953acb187e624763             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:44.678000+00:00 2026-07-18 21:42:45.147000+00:00               0.005464             0.005073        0.007733                0.005942                0.146739
33   329083b8eb4e422ba140cc930dc72306             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:41.720000+00:00 2026-07-18 21:42:42.194000+00:00               0.061639             0.032807        0.049253                0.099201                1.373056
34   1478e05c9c104201ab39a52cc7f2f7b5             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:39.823000+00:00 2026-07-18 21:42:40.228000+00:00               0.103768             0.058518        0.051474                0.144059                1.493015
35   6e91fc61ea8742599c47b9206b732a25             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:37.061000+00:00 2026-07-18 21:42:37.489000+00:00               0.068456             0.029015        0.038532                0.098058                1.266839
36   f382bcc68f314d15affc0db86ec3db11             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:34.061000+00:00 2026-07-18 21:42:34.492000+00:00               0.006747             0.018058        0.023475                0.009472                0.146138
37   740b17f4357649839040f2cae8a4020e             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:32.432000+00:00 2026-07-18 21:42:32.818000+00:00               0.021629             0.013028        0.019590                0.031652                0.146321
38   279bdfe13b594efabd6e64ce4c6a65a0             8  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:29.602000+00:00 2026-07-18 21:42:30.001000+00:00               0.004470             0.008628        0.014642                0.007225                0.130322
39   e715806c2a844161940684fd407bdc04             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:26.694000+00:00 2026-07-18 21:42:27.144000+00:00               0.153521             0.008863        0.010002                0.190009                2.333258
40   d16e9c985f534bd3877a4c95daa5418a             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:24.885000+00:00 2026-07-18 21:42:25.278000+00:00               0.174537             0.006762        0.009570                0.228336                2.319261
41   303f20dea5854c39816109a8e7a18096             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:22.071000+00:00 2026-07-18 21:42:22.527000+00:00               0.111393             0.007270        0.008726                0.148457                2.100767
42   b2e197e932ee4854a2c97db953889a8f             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:18.956000+00:00 2026-07-18 21:42:19.473000+00:00               0.294058             0.007627        0.009775                0.378056                2.877165
43   ef393cf619ba4a6fbc96aeeaf5c35365             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:17.192000+00:00 2026-07-18 21:42:17.576000+00:00               0.154103             0.007818        0.010140                0.135044                3.129273
44   993d20596ef84933b7a87d7fb2611694             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:14.334000+00:00 2026-07-18 21:42:14.877000+00:00               0.107212             0.004269        0.007662                0.122478                2.520594
45   e05a81c9d8514f0892d4a6e7126b9f7a             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:11.388000+00:00 2026-07-18 21:42:11.869000+00:00               0.080881             0.213604        0.204939                0.117612                1.119527
46   8258a431287a47d191355f3c0e0c5e7e             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:09.624000+00:00 2026-07-18 21:42:10.004000+00:00               0.255015             0.237686        0.522750                0.369541                1.898647
47   372cf86eb8cd4cb5a4709ef79ae3c85a             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:06.105000+00:00 2026-07-18 21:42:06.595000+00:00               0.053263             0.257581        0.311854                0.073590                1.408817
48   85dc35d252254c3481ff0945b62528b7             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:03.060000+00:00 2026-07-18 21:42:03.521000+00:00               0.233869             0.164369        0.106837                0.370619                4.373000
49   cbce2681bd944fe6bc423b6c7bd88bb1             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:42:01.240000+00:00 2026-07-18 21:42:01.637000+00:00               0.529056             0.118536        0.103852                0.638025                4.280934
50   21812dc6da8c40f4a5623fff7c83d3b4             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:57.748000+00:00 2026-07-18 21:41:58.212000+00:00               0.152200             0.104230        0.082133                0.204936                3.936300
51   28adaf492cd44268a29f19b4d7c6ef44             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:54.767000+00:00 2026-07-18 21:41:55.309000+00:00               0.011521             0.034180        0.045066                0.019405                0.204053
52   300fbbb0da6945e7a83878ed7826f203             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:52.999000+00:00 2026-07-18 21:41:53.390000+00:00               0.039256             0.036616        0.063641                0.046184                0.241431
53   f686510cfadf4048b77ab7b077aa5f09             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:50.050000+00:00 2026-07-18 21:41:50.502000+00:00               0.009929             0.033836        0.045466                0.012391                0.189381
54   d1a219c7ecf449198119563a4fdd4597             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:47.092000+00:00 2026-07-18 21:41:47.578000+00:00               0.053135             0.039858        0.047935                0.068402                1.047991
55   60dbfb63b5a243b5bc86b6e613ff600b             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:45.264000+00:00 2026-07-18 21:41:45.687000+00:00               0.074890             0.054947        0.048654                0.092597                1.216244
56   41a07ad373b4459d8d8ca503f5b81ab0             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:42.384000+00:00 2026-07-18 21:41:42.836000+00:00               0.044296             0.059359        0.054116                0.053236                1.060734
57   9df89a67d6ef46169d1ddc9188f3f620             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:39.366000+00:00 2026-07-18 21:41:39.847000+00:00               0.005734             0.055552        0.066086                0.010298                0.190657
58   bee8d020da454107a09878669d05a84b             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:37.621000+00:00 2026-07-18 21:41:38.029000+00:00               0.034616             0.089865        0.093578                0.045301                0.225994
59   91efead6ba3e430da6d494201ebc2f2a             7  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:34.637000+00:00 2026-07-18 21:41:35.171000+00:00               0.009856             0.051558        0.054974                0.012596                0.171167
60   b7df61b9c99149278ff3d1ba73eb4545             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:31.609000+00:00 2026-07-18 21:41:32.065000+00:00               0.086508             0.194615        0.219680                0.363230                3.661759
61   d975c122a0ee4d24824af22622dbb0d1             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:41:25.473000+00:00 2026-07-18 21:41:25.871000+00:00               0.919412             1.204500        1.262269                1.620947               11.161792
62   636cf48830fd4ed09650030aa7df6a13             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:40:32.941000+00:00 2026-07-18 21:40:33.341000+00:00               0.074792             0.155423        0.197856                0.232943                3.464469
63   966afa4ee8c04a79bb4cfb861b03dbae             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:40:21.040000+00:00 2026-07-18 21:40:21.434000+00:00               0.181404             0.158628        0.188753                0.392117                3.816380
64   c7601a936de24e5786c03ba797fbcd3a             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:40:12.234000+00:00 2026-07-18 21:40:12.626000+00:00               0.112142             0.211249        0.414408                0.184381                4.982067
65   173542ec3b784a65a72b6900765dddf3             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:40:04.764000+00:00 2026-07-18 21:40:04.980000+00:00               0.069248             0.188431        0.292381                0.152518                4.803601
66   972ce13a7dfb4a0c818cd140a5c66635             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:39:54.993000+00:00 2026-07-18 21:39:55.381000+00:00               0.186742             0.119628        0.228981                0.363942                3.602656
67   3008e7e28f2a4f02abb46d61bc188c60             6  FINISHED  file:///C:/Users/mohammadhosein/Desktop/surrog... 2026-07-18 21:39:52.516000+00:00 2026-07-18 21:39:52.936000+00:00               0.169477             0.093442        0.192406                0.310366                7.331517

==========================================================================================
3) BEST RUN PER EXPERIMENT (highest mean test R2)
==========================================================================================

,experiment_name,run_id,status,metrics.train_mae_std,metrics.test_r2_std,metrics.gap_r2,metrics.train_rmse_std,metrics.test_rmse_mean,metrics.test_mae_mean,metrics.train_rmse_mean,metrics.train_nrmse_mean,metrics.train_mae_mean,metrics.gap_rmse,metrics.train_r2_std,metrics.test_nrmse_std,metrics.train_r2_mean,metrics.test_nrmse_mean,metrics.test_rmse_std,metrics.test_r2_mean,metrics.train_nrmse_std,metrics.test_mae_std,params.discrete,params.model,params.mode,params.targets,params.dataset,params.target,tags.mlflow.runName
0,pipeline1_Dataset_0136,4eb3fadfe0fa466299eb959f67642603,FINISHED,0.091892,0.002644,0.003927,0.099648,1.470655,1.195909,0.613733,0.006428,0.486941,0.856922,0.000206,0.007028,0.999405,0.022331,0.368590,0.995478,0.001140,0.316250,False,gpr,single_output,None,Dataset_0136,Strain,gpr__Strain
1,pipeline4_Dataset_0136,c3247d41699340b7957cdc29ff32d415,FINISHED,0.067925,0.040665,0.070091,0.119463,2.332151,1.387738,0.999666,0.002336,0.573578,1.332485,0.002575,0.001186,0.986940,0.005690,0.507603,0.916849,0.000279,0.248628,True,lightgbm,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_0136,None,lightgbm__multi
2,pipeline4_Dataset_0172,d569127de58446e6b094f0c72cefd8c4,FINISHED,0.054673,0.024416,0.058853,0.160005,2.648487,1.231394,1.454139,0.007980,0.677201,1.194348,0.003122,0.003563,0.977683,0.015247,0.647393,0.918830,0.000911,0.215759,True,xgboost,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_0172,None,xgboost__multi
3,pipeline4_Dataset_3772,80dcf225f9ee4008b9c43407603a8166,FINISHED,0.074792,0.155423,0.197856,0.232943,3.464469,1.689501,1.427529,0.007841,0.701445,2.036940,0.004768,0.006268,0.970795,0.020036,1.017304,0.772938,0.001344,0.394142,True,xgboost,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_3772,None,xgboost__multi
4,pipeline1_Dataset_0172,92223c0543ad4087b0d34681d9be7ab6,FINISHED,0.005464,0.005073,0.007733,0.005942,0.146739,0.110221,0.089248,0.015201,0.067008,0.057492,0.000442,0.006172,0.996152,0.030715,0.041609,0.988418,0.001120,0.024934,False,xgboost,single_output,None,Dataset_0172,wear rate,xgboost__wear rate
5,pipeline1_Dataset_3772,043574f85f604a0488fe6015674f1680,FINISHED,0.002621,0.050311,0.057816,0.003097,0.050198,0.039668,0.026183,0.034563,0.019312,0.024015,0.004513,0.032863,0.983774,0.090063,0.025224,0.925959,0.005963,0.018491,False,xgboost,single_output,None,Dataset_3772,Si Particle Size (um),xgboost__Si Particle Size (um)
6,pipeline2_Dataset_0136,98eacf5ad3d44f67ba6d4c4c9aca9a09,FINISHED,0.067925,0.040665,0.070091,0.119463,2.332151,1.387738,0.999666,0.002336,0.573578,1.332485,0.002575,0.001186,0.986940,0.005690,0.507603,0.916849,0.000279,0.248628,False,lightgbm,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_0136,None,lightgbm__multi
7,pipeline2_Dataset_0172,97ae7299bf2e4730b20940be813e9386,FINISHED,0.054673,0.024416,0.058853,0.160005,2.648487,1.231394,1.454139,0.007980,0.677201,1.194348,0.003122,0.003563,0.977683,0.015247,0.647393,0.918830,0.000911,0.215759,False,xgboost,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_0172,None,xgboost__multi
8,pipeline2_Dataset_3772,636cf48830fd4ed09650030aa7df6a13,FINISHED,0.074792,0.155423,0.197856,0.232943,3.464469,1.689501,1.427529,0.007841,0.701445,2.036940,0.004768,0.006268,0.970795,0.020036,1.017304,0.772938,0.001344,0.394142,False,xgboost,multi_output,"Si Particle Size (um),Hardness (HV),wear rate,...",Dataset_3772,None,xgboost__multi
9,pipeline3_Dataset_0136,153223baea114afdb58a9171747082af,FINISHED,0.107212,0.004269,0.007662,0.122478,2.520594,2.156492,0.904912,0.007748,0.726056,1.615682,0.000319,0.009012,0.999068,0.030272,0.734421,0.991406,0.001217,0.642343,True,xgboost,single_output,None,Dataset_0136,Temperature (°C),xgboost__Temperature (°C)
10,pipeline3_Dataset_0172,ab1e3d2cd1cb466d953acb187e624763,FINISHED,0.005464,0.005073,0.007733,0.005942,0.146739,0.110221,0.089248,0.015201,0.067008,0.057492,0.000442,0.006172,0.996152,0.030715,0.041609,0.988418,0.001120,0.024934,True,xgboost,single_output,None,Dataset_0172,wear rate,xgboost__wear rate
11,pipeline3_Dataset_3772,995f358ba3e04d739a10526fe89a4570,FINISHED,0.002621,0.050311,0.057816,0.003097,0.050198,0.039668,0.026183,0.034563,0.019312,0.024015,0.004513,0.032863,0.983774,0.090063,0.025224,0.925959,0.005963,0.018491,True,xgboost,single_output,None,Dataset_3772,Si Particle Size (um),xgboost__Si Particle Size (um)

MLflow tracking store: C:\Users\mohammadhosein\Desktop\DeepLearning-miniProject\mlflow.db
Launch the UI with: mlflow ui --backend-store-uri sqlite:///mlflow.db
Summary tables saved to: C:\Users\mohammadhosein\Desktop\DeepLearning-miniProject\results\mlflow